Repository woowacourse-teams/2024-mouda, pull requests merged in 2024-08, with the labels that each got.

#168 로그인 API 스웨거 문서 작성
  backend/src/main/java/mouda/backend/auth/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/controller/AuthSwagger.java
Labels: BE, 📜 문서

#165 채팅 데이터 생성 및 모임마다의 전체 조회 기능 구현
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/dto/request/ChatCreateRequest.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindUnloadedResponse.java
  backend/src/main/java/mouda/backend/chat/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/chat/exception/ChatException.java
  backend/src/main/java/mouda/backend/chat/repository/ChatRepository.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/test/java/mouda/backend/chat/repository/ChatRepositoryTest.java
  backend/src/test/java/mouda/backend/fixture/ChatFixture.java
  backend/src/test/java/mouda/backend/fixture/MoimFixture.java
Labels: BE, 🌱 기능추가

#164 채팅을 위한 컴포넌트 구현
  frontend/.storybook/main.ts
  frontend/src/common/assets/default_profile.png
  frontend/src/common/assets/meatball.svg
  frontend/src/common/assets/plus.svg
  frontend/src/common/assets/x.svg
  frontend/src/components/Chat/Chat.stories.tsx
  frontend/src/components/Chat/Chat.tsx
  frontend/src/components/Chat/Chatstyle.ts
  frontend/src/components/ChatList/ChatList.stories.tsx
  frontend/src/components/ChatList/ChatList.style.ts
  frontend/src/components/ChatList/ChatList.tsx
  frontend/src/components/ChattingFooter/ChattingFooter.stories.tsx
  frontend/src/components/ChattingFooter/ChattingFooter.style.ts
  frontend/src/components/ChattingFooter/ChattingFooter.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.stories.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.style.ts
  frontend/src/components/ChattingPreview/ChattingPreview.tsx
  frontend/src/components/Icons/SendButton.tsx
  frontend/src/components/UserPreview/UserPreview.stories.tsx
  frontend/src/components/UserPreview/UserPreview.style.ts
  frontend/src/components/UserPreview/UserPreview.tsx
  frontend/src/components/UserPreviewList/UserPreviewList.stories.tsx
  frontend/src/components/UserPreviewList/UserPreviewList.style.ts
  frontend/src/components/UserPreviewList/UserPreviewList.tsx
  frontend/src/constants/poclies.ts
  frontend/src/utils/formatters.ts
Labels: FE, 🌱 기능추가

#169 모임 댓글 기능 구현
  backend/src/main/java/mouda/backend/comment/domain/Comment.java
  backend/src/main/java/mouda/backend/comment/dto/request/CommentCreateRequest.java
  backend/src/main/java/mouda/backend/comment/dto/response/ChildCommentResponse.java
  backend/src/main/java/mouda/backend/comment/dto/response/CommentResponse.java
  backend/src/main/java/mouda/backend/comment/exception/CommentErrorMessage.java
  backend/src/main/java/mouda/backend/comment/exception/CommentException.java
  backend/src/main/java/mouda/backend/comment/repository/CommentRepository.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/controller/MoimSwagger.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimDetailsFindResponse.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/test/java/mouda/backend/comment/domain/CommentTest.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/fixture/CommentFixture.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 🌱 기능추가

#171 모임 상태 및 찜, 참여 기능 추가
  backend/src/main/java/mouda/backend/auth/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/controller/AuthSwagger.java
  backend/src/main/java/mouda/backend/auth/dto/request/LoginRequest.java
  backend/src/main/java/mouda/backend/auth/dto/response/LoginResponse.java
  backend/src/main/java/mouda/backend/auth/service/AuthService.java
  backend/src/main/java/mouda/backend/chamyo/controller/ChamyoController.java
  backend/src/main/java/mouda/backend/chamyo/controller/ChamyoSwagger.java
  backend/src/main/java/mouda/backend/chamyo/domain/Chamyo.java
  backend/src/main/java/mouda/backend/chamyo/domain/MoimRole.java
  backend/src/main/java/mouda/backend/chamyo/dto/request/MoimChamyoRequest.java
  backend/src/main/java/mouda/backend/chamyo/dto/response/ChamyoFindAllResponse.java
  backend/src/main/java/mouda/backend/chamyo/dto/response/ChamyoFindAllResponses.java
  backend/src/main/java/mouda/backend/chamyo/dto/response/MoimRoleFindResponse.java
  backend/src/main/java/mouda/backend/chamyo/exception/ChamyoErrorMessage.java
  backend/src/main/java/mouda/backend/chamyo/exception/ChamyoException.java
  backend/src/main/java/mouda/backend/chamyo/repository/ChamyoRepository.java
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/controller/MoimSwagger.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/domain/MoimStatus.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
  backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
  backend/src/main/java/mouda/backend/moim/repository/MoimRepository.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/zzim/controller/ZzimController.java
  backend/src/main/java/mouda/backend/zzim/controller/ZzimSwagger.java
  backend/src/main/java/mouda/backend/zzim/domain/Zzim.java
  backend/src/main/java/mouda/backend/zzim/dto/request/ZzimUpdateRequest.java
  backend/src/main/java/mouda/backend/zzim/dto/response/ZzimCheckResponse.java
  backend/src/main/java/mouda/backend/zzim/exception/ZzimErrorMessage.java
  backend/src/main/java/mouda/backend/zzim/exception/ZzimException.java
  backend/src/main/java/mouda/backend/zzim/repository/ZzimRepository.java
  backend/src/main/java/mouda/backend/zzim/service/ZzimService.java
  backend/src/test/java/mouda/backend/auth/controller/AuthControllerTest.java
  backend/src/test/java/mouda/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/mouda/backend/chamyo/controller/ChamyoControllerTest.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/fixture/TokenFixture.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
  backend/src/test/java/mouda/backend/zzim/controller/ZzimControllerTest.java
Labels: BE, 🌱 기능추가

#167 로그인 기능 개발
  frontend/.storybook/main.ts
  frontend/jest.config.ts
  frontend/src/App.tsx
  frontend/src/apis/apiClient.ts
  frontend/src/apis/auth.ts
  frontend/src/apis/endPoints.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/components/LoginForm/LoginForm.tsx
  frontend/src/routes/ProtectedRoute.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/checkAuthentication.ts
  frontend/src/utils/tokenManager.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE, 🌱 기능추가

#170 코멘트 section 구현
  frontend/src/common/assets/submit_message_button.svg
  frontend/src/components/CommentCard/CommentCard.stories.tsx
  frontend/src/components/CommentCard/CommentCard.style.ts
  frontend/src/components/CommentCard/CommentCard.tsx
  frontend/src/components/CommentList/ComentList.style.ts
  frontend/src/components/CommentList/ComentList.tsx
  frontend/src/components/CommentList/CommentList.stories.tsx
  frontend/src/components/Input/MessagInput/MessageInput.stories.tsx
  frontend/src/components/Input/MessagInput/MessageInput.style.ts
  frontend/src/components/Input/MessagInput/MessageInput.tsx
  frontend/src/components/Profile/ProfileCard.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#191 채팅 기능에서 인증된 맴버만 사용할 수 있게 수정
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
Labels: BE, ⚒️ 리팩터링

#192 채팅 조회 기능 API 스팩 변경
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindUnloadedResponse.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
Labels: BE, ⚒️ 리팩터링

#194 나의 채팅이 잘못 확인되는 버그 수정
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
Labels: BE, 🚑 버그

#196 CORS 허용 메소드에 PATCH 메서드 추가
  backend/src/main/java/mouda/backend/config/CorsConfig.java
Labels: BE, 🌱 기능추가

#197 나의 모임 조회, 찜한 모임 조회 기능 구현
  backend/src/main/java/mouda/backend/chamyo/repository/ChamyoRepository.java
  backend/src/main/java/mouda/backend/config/WebMvcConfig.java
  backend/src/main/java/mouda/backend/config/converter/FilterTypeConverter.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/controller/MoimSwagger.java
  backend/src/main/java/mouda/backend/moim/domain/FilterType.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimFindAllResponse.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/zzim/repository/ZzimRepository.java
  backend/src/test/java/mouda/backend/config/ChamyoCreator.java
  backend/src/test/java/mouda/backend/member/repository/MemberRepositoryTest.java
  backend/src/test/java/mouda/backend/moim/MoimControllerTest.java
  backend/src/test/java/mouda/backend/moim/controller/MoimControllerTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 🌱 기능추가

#179 상세페이지의 찜 버튼과 케밥 메뉴 버튼 UI 구현
  frontend/src/common/assets/kebab_menu.svg
  frontend/src/common/assets/zzim_emty_button.svg
  frontend/src/common/assets/zzim_fill_button.svg
  frontend/src/components/CommentList/CommentList.stories.tsx
  frontend/src/components/CommentList/CommentList.tsx
  frontend/src/components/KebabMenu/KababMenu.stories.tsx
  frontend/src/components/KebabMenu/KebabMenu.style.ts
  frontend/src/components/KebabMenu/KebabMenu.tsx
  frontend/src/components/Zzim/ZzimButton.stories.tsx
  frontend/src/components/Zzim/ZzimButton.style.ts
  frontend/src/components/Zzim/ZzimButton.tsx
Labels: FE, 🌱 기능추가

#181 홈(모임 목록) 페이지 UI 개발!
  frontend/src/components/Card/MoimCard.style.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/components/Icons/HeartIcon.tsx
  frontend/src/components/Icons/PlusIcon.tsx
  frontend/src/components/LoginForm/LoginForm.stories.tsx
  frontend/src/components/MoimCard/MoimCard.stories.tsx
  frontend/src/components/MoimCard/MoimCard.style.ts
  frontend/src/components/MoimCard/MoimCard.tsx
  frontend/src/components/MoimCardList/MoimCardList.stories.tsx
  frontend/src/components/MoimCardList/MoimCardList.style.ts
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/components/MoimTabBar/MoimTabBar.stories.tsx
  frontend/src/components/MoimTabBar/MoimTabBar.style.ts
  frontend/src/components/MoimTabBar/MoimTabBar.tsx
  frontend/src/components/MyMoimListFilterTag/MyMoimListFilterTag.stories.tsx
  frontend/src/components/MyMoimListFilterTag/MyMoimListFilterTag.style.ts
  frontend/src/components/MyMoimListFilterTag/MyMoimListFilterTag.tsx
  frontend/src/components/MyMoimListFilters/MyMoimListFilters.stories.tsx
  frontend/src/components/MyMoimListFilters/MyMoimListFilters.style.ts
  frontend/src/components/MyMoimListFilters/MyMoimListFilters.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeNav/HomeNav.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeNav/HomeNav.tsx
  frontend/src/pages/MainPage/MainPage.stories.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#182 채팅 레이아웃 구현 및 페이지 구현
  frontend/src/constants/routes.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.stories.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewLayout.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewLayout.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomFooter/ChattingRoomFooter.style.ts
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomFooter/ChattingRoomFooter.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.stories.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.style.ts
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.tsx
  frontend/src/layouts/components/StickyTriSectionHeader/StickyTriSectionHeader.style.ts
  frontend/src/layouts/components/StickyTriSectionHeader/StickyTriSectionHeader.tsx
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🌱 기능추가

#184 채팅 컴포넌트 버그 수정
  frontend/src/components/ChatList/ChatList.style.ts
  frontend/src/components/ChatList/ChatList.tsx
  frontend/src/components/ChattingFooter/ChattingFooter.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.style.ts
Labels: FE, 🚑 버그

#186 MoimDetail 페이지에 피그마 추가된 요구사항에 맞게 수정
  frontend/src/components/MoimDescription/MoimDescription.style.ts
  frontend/src/components/MoimDescription/MoimDescription.tsx
  frontend/src/components/MoimInformation/MoimInformation.style.ts
  frontend/src/components/MoimInformation/MoimInformation.tsx
  frontend/src/components/MoimSummary/MoimSummary.stories.tsx
  frontend/src/components/MoimSummary/MoimSummary.style.ts
  frontend/src/components/MoimSummary/MoimSummary.tsx
  frontend/src/components/ProfileList/ProfileList.tsx
  frontend/src/components/Tag/Tag.stories.tsx
  frontend/src/components/Tag/Tag.style.ts
  frontend/src/components/Tag/Tag.tsx
  frontend/src/mocks/handlers/moimHandler.ts
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#204 `@LoginMember`가 스웨거 파라미터에 포함되지 않도록 수정. 인증 정보 입력할 수 있도록 수정
  backend/src/main/java/mouda/backend/config/SwaggerConfig.java
Labels: BE, 🚑 버그

#207 채팅 API의 스웨거 문서를 위한 인터페이스 구현
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/controller/ChatSwagger.java
Labels: BE, 🌱 기능추가

#209 feat: 환경별 application 분리
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
Labels: BE, 🌱 기능추가

#200 홈(모임 목록) 비즈니스 로직 및 API 연동 작업
  frontend/src/apis/gets.ts
  frontend/src/components/HomeMainContent/HomeMainContent.tsx
  frontend/src/components/MoimCard/MoimCard.stories.tsx
  frontend/src/components/MoimCard/MoimCard.style.ts
  frontend/src/components/MoimCard/MoimCard.tsx
  frontend/src/components/MoimCardList/MoimCardList.stories.tsx
  frontend/src/components/MoimList/MoimList.tsx
  frontend/src/components/MoimTabBar/MoimTabBar.stories.tsx
  frontend/src/components/MoimTabBar/MoimTabBar.tsx
  frontend/src/components/MyMoim/MyMoim.tsx
  frontend/src/components/MyMoimListFilters/MyMoimListFilters.stories.tsx
  frontend/src/components/MyMoimListFilters/MyMoimListFilters.tsx
  frontend/src/components/MyZzimMoimList/MyZzimMoimList.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/mutaions/useChangeZzim.ts
  frontend/src/hooks/queries/useMyMoims.ts
  frontend/src/hooks/queries/useMyZzimMoim.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#205 하단 NavigationBar 구현
  frontend/src/components/Icons/ChattingIcon.tsx
  frontend/src/components/Icons/HomeIcon.tsx
  frontend/src/components/Icons/MyPageIcon.tsx
  frontend/src/components/Icons/PleaseIcon.tsx
  frontend/src/components/MoimCard/MoimCard.stories.tsx
  frontend/src/components/MoimCardList/MoimCardList.stories.tsx
  frontend/src/components/NavigationBar/NavigationBar.stories.tsx
  frontend/src/components/NavigationBar/NavigationBar.style.ts
  frontend/src/components/NavigationBar/NavigationBar.tsx
  frontend/src/components/NavigationBarItem/NavigationBarItem.style.ts
  frontend/src/components/NavigationBarItem/NavigationBarItem.tsx
  frontend/src/constants/routes.ts
  frontend/src/constants/styles.ts
  frontend/src/layouts/HomeLayout.tsx/HomeFixedButtonWrapper/HomeFixedButtonWrapper.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/MoimList.style.ts
  frontend/src/layouts/components/NavigationBarWrapper/NavigationBarWrapper.style.ts
  frontend/src/layouts/components/NavigationBarWrapper/NavigationBarWrapper.tsx
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
Labels: FE, 🌱 기능추가

#203 모임 상태 타입 변경, MoimInfo 타입추가, 라우팅 수정
  frontend/src/apis/deletes.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/LoginForm/LoginForm.tsx
  frontend/src/components/MoimCardList/MoimCardList.stories.tsx
  frontend/src/components/MoimSummary/MoimSummary.stories.tsx
  frontend/src/components/ProfileList/ProfileList.tsx
  frontend/src/components/Tag/Tag.stories.tsx
  frontend/src/components/Tag/Tag.style.ts
  frontend/src/components/Tag/Tag.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가, 🚑 버그

#214 채팅 페이지 api 통합
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/components/Chat/Chat.stories.tsx
  frontend/src/components/Chat/Chat.tsx
  frontend/src/components/ChatList/ChatList.stories.tsx
  frontend/src/components/ChatList/ChatList.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.stories.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.tsx
  frontend/src/components/ChattingPreviewWrapper/ChattingPreviewWrapper.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/mutaions/useSendMessage.ts
  frontend/src/hooks/queries/useChat.ts
  frontend/src/hooks/queries/useMyMoim.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.stories.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.style.ts
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.stories.tsx
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#217 프론트엔드 병합에서 발생한 타입 문제, 이중 선언 문제 조정
  frontend/src/apis/gets.ts
  frontend/src/components/ChatList/ChatList.style.ts
  frontend/src/components/ChatList/ChatList.tsx
  frontend/src/components/MoimCard/MoimCard.stories.tsx
  frontend/src/components/MoimCardList/MoimCardList.stories.tsx
  frontend/src/hooks/queries/useMyMoims.ts
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
Labels: FE, 🚑 버그

#225 로그인 토큰 만료시 에러 핸들링
  frontend/src/apis/apiClient.ts
  frontend/src/apis/apiconfig.ts
  frontend/src/apis/auth.ts
  frontend/src/apis/deletes.ts
  frontend/src/apis/fetchs.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/queryClient.ts
  frontend/src/utils/customError/ApiError.ts
Labels: FE, 🌱 기능추가

#233 해주세요 및 관심 도메인 추가
  backend/src/main/java/mouda/backend/please/domain/Interest.java
  backend/src/main/java/mouda/backend/please/domain/Please.java
Labels: BE, 🌱 기능추가

#231 마이페이지 API 구현
  backend/src/main/java/mouda/backend/auth/controller/AuthController.java
  backend/src/main/java/mouda/backend/member/controller/MemberController.java
  backend/src/main/java/mouda/backend/member/controller/MemberSwagger.java
  backend/src/main/java/mouda/backend/member/dto/response/MemberFindResponse.java
  backend/src/main/java/mouda/backend/member/service/MemberService.java
  backend/src/test/java/mouda/backend/auth/controller/AuthControllerTest.java
  backend/src/test/java/mouda/backend/member/controller/MemberControllerTest.java
Labels: BE, 🌱 기능추가

#239 모임 도메인 isConfirmChat 구현 및 채팅 내용 수정
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindDetailResponse.java
Labels: BE, ⚒️ 리팩터링

#226 모임 상세 페이지, 모임 수정 페이지 QA 수정
  frontend/src/apis/fetchs.ts
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Chat/Chat.tsx
  frontend/src/components/CommentCard/CommentCard.style.ts
  frontend/src/components/CommentCard/CommentCard.tsx
  frontend/src/components/CommentList/CommentList.tsx
  frontend/src/components/MoimSummary/MoimSummary.stories.tsx
  frontend/src/components/MoimSummary/MoimSummary.tsx
  frontend/src/components/Profile/ProfileFrame.style.ts
  frontend/src/components/Profile/ProfileFrame.tsx
  frontend/src/components/Zzim/ZzimButton.stories.tsx
  frontend/src/components/Zzim/ZzimButton.tsx
  frontend/src/hooks/mutaions/useModifyMoim.ts
  frontend/src/layouts/InformationLayout/InformationLayout.tsx
  frontend/src/pages/MoimCreationPage/MoimCreatePage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreatePage.util.test.tsx
  frontend/src/pages/MoimCreationPage/MoimCreatePage.util.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.constant.ts
  frontend/src/pages/MoimCreationPage/useMoimInfoInput.test.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/MoimModifyPage/MoimModifyPage.hook.ts
  frontend/src/pages/MoimModifyPage/MoimModifyPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#234 채팅방 메시지 도착 시 하단으로 가지지 않는 버그 수정
  frontend/src/components/Chat/Chatstyle.ts
  frontend/src/components/ChatList/ChatList.style.ts
  frontend/src/components/ChatList/ChatList.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.style.ts
Labels: FE, 🚑 버그

#223 Interceptor의 Preflight 처리 로직 개선
  backend/src/main/java/mouda/backend/config/interceptor/AuthenticationCheckInterceptor.java
Labels: BE, ⚒️ 리팩터링

#243 해주세요 전체 목록 조회 기능 구현
  backend/src/main/java/mouda/backend/please/controller/PleaseController.java
  backend/src/main/java/mouda/backend/please/dto/response/PleaseFindAllResponse.java
  backend/src/main/java/mouda/backend/please/dto/response/PleaseFindAllResponses.java
  backend/src/main/java/mouda/backend/please/repository/InterestRepository.java
  backend/src/main/java/mouda/backend/please/repository/PleaseRepository.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/test/java/mouda/backend/fixture/PleaseFixture.java
  backend/src/test/java/mouda/backend/please/controller/PleaseControllerTest.java
Labels: BE, 🌱 기능추가

#244 해주세요 작성 및 삭제 기능 구현
  backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/please/controller/PleaseController.java
  backend/src/main/java/mouda/backend/please/controller/PleaseSwagger.java
  backend/src/main/java/mouda/backend/please/domain/Please.java
  backend/src/main/java/mouda/backend/please/dto/request/PleaseCreateRequest.java
  backend/src/main/java/mouda/backend/please/exception/PleaseErrorMessage.java
  backend/src/main/java/mouda/backend/please/exception/PleaseException.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/fixture/PleaseFixture.java
  backend/src/test/java/mouda/backend/please/service/PleaseServiceTest.java
Labels: BE, 🌱 기능추가

#247 채팅방 목록 미리보기 api 구현 및 마지막으로 읽은 채팅 필드 추가
  backend/src/main/java/mouda/backend/chamyo/domain/Chamyo.java
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/controller/ChatSwagger.java
  backend/src/main/java/mouda/backend/chat/dto/request/LastReadChatRequest.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatPreviewResponse.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatPreviewResponses.java
  backend/src/main/java/mouda/backend/chat/repository/ChatRepository.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/test/java/mouda/backend/chat/repository/ChatRepositoryTest.java
  backend/src/test/java/mouda/backend/chat/service/ChatServiceTest.java
  backend/src/test/java/mouda/backend/config/ChamyoCreator.java
Labels: BE, 🌱 기능추가

#259 버튼 컴포넌트와 emotion/theme을 유연화
  frontend/src/common/theme/coloredTypography.ts
  frontend/src/common/theme/semantic.ts
  frontend/src/common/theme/theme.type.ts
  frontend/src/components/Button/Button.stories.tsx
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#257 관심있어요 상태 변경 기능 구현
  backend/src/main/java/mouda/backend/please/controller/InterestController.java
  backend/src/main/java/mouda/backend/please/controller/InterestSwagger.java
  backend/src/main/java/mouda/backend/please/domain/Interest.java
  backend/src/main/java/mouda/backend/please/dto/request/InterestUpdateRequest.java
  backend/src/main/java/mouda/backend/please/exception/PleaseErrorMessage.java
  backend/src/main/java/mouda/backend/please/repository/InterestRepository.java
  backend/src/main/java/mouda/backend/please/service/InterestService.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/please/controller/InterestControllerTest.java
Labels: BE, 🌱 기능추가

#255 홈, 해주세요 페이지 레이아웃 및 스타일링 수정
  frontend/src/components/HomeHeaderContent/HomHeaderContent.tsx
  frontend/src/components/HomeHeaderContent/HomeHeaderContent.style.ts
  frontend/src/components/MoimCard/MoimCard.style.ts
  frontend/src/components/MoimCard/MoimCard.tsx
  frontend/src/components/MoimTabBar/MoimTabBar.style.ts
  frontend/src/components/MoimTabBar/MoimTabBar.tsx
  frontend/src/components/PleaseCard/PleaseCard.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.tsx
  frontend/src/layouts/PleaseLayout/PleaseLayout.style.ts
  frontend/src/layouts/PleaseLayout/PleaseLayout.tsx
  frontend/src/layouts/PleaseLayout/PleaseMain/PleaseMain.style.ts
  frontend/src/layouts/PleaseLayout/PleaseMain/PleaseMain.tsx
  frontend/src/pages/MainPage/MainPage.tsx
Labels: FE, 🚑 버그

#260 작성자가 채팅방을 여는 기능 구현
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/controller/ChatSwagger.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatPreviewResponse.java
  backend/src/main/java/mouda/backend/chat/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
Labels: BE, 🌱 기능추가

#262 관심 상태 변경시 해주세요 목록 전체에 관심 상태 표기가 변경되는 오류 수정
  backend/src/main/java/mouda/backend/please/service/InterestService.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/test/java/mouda/backend/please/controller/InterestControllerTest.java
  backend/src/test/java/mouda/backend/please/service/PleaseServiceTest.java
Labels: BE, 🚑 버그

#263 해주세요의 관심있어요 기능 API 스펙 변경 대응
  frontend/src/apis/posts.ts
  frontend/src/mocks/handlers/interestHandler.ts
  frontend/src/mocks/handlers/mockPleases.ts
Labels: FE, 🚑 버그

#248 채팅방에서 날짜, 시간, 장소를 확정하는 기능 구현
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/controller/ChatSwagger.java
  backend/src/main/java/mouda/backend/chat/dto/request/DateTimeConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/dto/request/PlaceConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/test/java/mouda/backend/chat/service/ChatServiceTest.java
Labels: BE, 🌱 기능추가

#261 리드미 모우다팀 정보 작성
  README.md
Labels: 📜 문서

#266 사용자 지표 모니터링을 위한 GA 세팅
  frontend/package-lock.json
  frontend/package.json
  frontend/src/RouteChageTracker.ts
  frontend/src/index.tsx
  frontend/src/routes/router.tsx
Labels: FE, ⚙ 환경설정

#268 채팅 추가 컴포넌트 및 페이지 구현
  frontend/src/common/theme/coloredTypography.ts
  frontend/src/common/theme/theme.style.ts
  frontend/src/common/theme/theme.type.ts
  frontend/src/components/Chat/Chat.stories.tsx
  frontend/src/components/Chat/Chat.tsx
  frontend/src/components/Chat/Chatstyle.ts
  frontend/src/components/ChatBottomMenu/ChatBottomMenu.stories.tsx
  frontend/src/components/ChatBottomMenu/ChatBottomMenu.style.ts
  frontend/src/components/ChatBottomMenu/ChatBottomMenu.tsx
  frontend/src/components/ChatBubble/ChatBubble.stories.tsx
  frontend/src/components/ChatBubble/ChatBubble.style.ts
  frontend/src/components/ChatBubble/ChatBubble.tsx
  frontend/src/components/ChatBubble/ChatChildren/ChatChildren.style.tsx
  frontend/src/components/ChatBubble/ChatChildren/ChatChildren.tsx
  frontend/src/components/ChatList/ChatList.stories.tsx
  frontend/src/components/ChatList/ChatList.tsx
  frontend/src/components/ChatMenuItem/ChatMenuItem.stories.tsx
  frontend/src/components/ChatMenuItem/ChatMenuItem.style.ts
  frontend/src/components/ChatMenuItem/ChatMenuItem.tsx
  frontend/src/components/ChattingFooter/ChattingFooter.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.stories.tsx
  frontend/src/components/ChattingPreview/ChattingPreview.style.ts
  frontend/src/components/ChattingPreview/ChattingPreview.tsx
  frontend/src/components/ChattingPreviewWrapper/ChattingPreviewWrapper.tsx
  frontend/src/components/DateTimeModalContent/DateTimeModalContent.stories.tsx
  frontend/src/components/DateTimeModalContent/DateTimeModalContent.style.ts
  frontend/src/components/DateTimeModalContent/DateTimeModalContent.tsx
  frontend/src/components/Icons/CalenderClock.tsx
  frontend/src/components/Icons/ChatBubbleSvg.tsx
  frontend/src/components/Icons/Picker.tsx
  frontend/src/components/Modal/Modal.style.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/PlaceModalContent/PlaceModalContent.stories.tsx
  frontend/src/components/PlaceModalContent/PlaceModalContent.style.ts
  frontend/src/components/PlaceModalContent/PlaceModalContent.tsx
  frontend/src/components/UserPreviewList/UserPreviewList.style.ts
  frontend/src/constants/poclies.ts
  frontend/src/emotion.d.ts
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.stories.tsx
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#271 홈, 해주세요 목록 / 하단 네비게이션 바 UI 수정
  frontend/.gitignore
  frontend/src/components/NavigationBarItem/NavigationBarItem.style.ts
  frontend/src/components/NavigationBarItem/NavigationBarItem.tsx
  frontend/src/components/PlusButton/PlusButton.style.ts
  frontend/src/components/PlusButton/PlusButton.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeFixedButtonWrapper/HomeFixedButtonWrapper.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.style.ts
  frontend/src/layouts/PleaseLayout/PleaseFixedButtonWrapper/PleaseFixedButtonWrapper.style.ts
  frontend/src/layouts/PleaseLayout/PleaseLayout.style.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/PleasePage/PleasePage.tsx
Labels: FE, 🚑 버그

#273 해주세요 생성 페이지, 훅 테스트 코드 작성
  frontend/src/pages/PleaseCreationPage/MoimCreatePage.util.test.tsx
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.hook.ts
  frontend/src/pages/PleaseCreationPage/useMoimInfoInput.test.tsx
Labels: FE, 👀 테스트

#277 token 접근 관련 예외 처리 로직 변경
  frontend/src/apis/apiClient.ts
  frontend/src/utils/checkAuthentication.ts
  frontend/src/utils/tokenManager.ts
Labels: FE, 🚑 버그

#278 테스트 환경에서 msw 모킹을 위한 세팅
  frontend/.storybook/main.ts
  frontend/jest.config.json
  frontend/jest.config.ts
  frontend/jest.polyfills.js
  frontend/jest.setup.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/queries/useMoims.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler/index.ts
  frontend/src/mocks/handler/interestHandler.ts
  frontend/src/mocks/handler/mockPleases.ts
  frontend/src/mocks/handler/moimHandler.ts
  frontend/src/mocks/handler/pleaseHandler.ts
  frontend/src/mocks/server.ts
  frontend/src/mocks/wrapper.tsx
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE, ⚙ 환경설정

#281 변수 불일치 버그 수정, 해주세요 만들기 페이지 라우터 연결
  frontend/src/constants/routes.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.tsx
  frontend/src/pages/PleasePage/PleasePage.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🚑 버그

#287 채팅방 api 명세 변경
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
  backend/src/main/java/mouda/backend/chat/domain/ChatType.java
  backend/src/main/java/mouda/backend/chat/dto/request/ChatCreateRequest.java
  backend/src/main/java/mouda/backend/chat/dto/request/DateTimeConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/dto/request/PlaceConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatPreviewResponse.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/test/java/mouda/backend/fixture/ChatFixture.java
Labels: BE, 🚑 버그

#284 로깅 프레임워크 도입 및 로깅 적용
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/mouda/backend/config/RequestBodyWrappingFilter.java
  backend/src/main/java/mouda/backend/config/WebMvcConfig.java
  backend/src/main/java/mouda/backend/config/interceptor/ApiRequestLoggingInterceptor.java
  backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
  backend/src/main/resources/log4j2-spring.xml
Labels: BE, 🌱 기능추가, ⚙ 환경설정

#290 배포한 서비스 모니터링 및 에러 디버깅 환경 구축
  .github/workflows/cd-frontend.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/RouteChageTracker.ts
  frontend/src/index.tsx
  frontend/src/queryClient.ts
  frontend/src/routes/router.tsx
  frontend/webpack.prod.js
Labels: FE, ⚙ 환경설정

#294 Logback 프레임워크로 로깅 설정 파일 수정
  backend/build.gradle
  backend/src/main/resources/log4j2-spring.xml
  backend/src/main/resources/logback-spring.xml
Labels: BE, ⚙ 환경설정

#299 프론트엔드 ci환경에 환경 변수 추가
  .github/workflows/ci-frontend.yml
Labels: FE, ⚙ 환경설정

#300 스토리북 환경에 msw 라우터 모킹 추가
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/LoginForm/LoginForm.stories.tsx
  frontend/src/components/MineInfoCard/MoinInfoCard.stories.tsx
  frontend/src/components/MoimCardList/MoimCardList.stories.tsx
  frontend/src/components/PleaseCard/PleaseCard.stories.tsx
  frontend/src/pages/MainPage/MainPage.stories.tsx
Labels: FE, ⚙ 환경설정

#295 채팅 테스트 구현
  frontend/jest.setup.ts
  frontend/src/apis/endPoints.ts
  frontend/src/components/MoimTabBar/MoimTabBar.stories.tsx
  frontend/src/hooks/queries/useChats.test.tsx
  frontend/src/hooks/queries/useChats.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler/chatHandler.ts
  frontend/src/mocks/handler/index.ts
  frontend/src/mocks/handler/mockedChats.ts
  frontend/src/mocks/handler/moimHandler.ts
  frontend/src/pages/ChattingRoomPage/ChattingRoomPage.tsx
Labels: FE, 👀 테스트

#304 input의 placeHolder을 사용자가 입력하는 값의 범위를 알 수 있게 표시
  frontend/src/pages/MoimCreationPage/MoimCreationPage.constant.ts
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.constant.ts
Labels: FE, 🌱 기능추가

#302 feat: moim 날짜, 시간, 장소 nullable 하도록 변경
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimEditRequest.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimDetailsFindResponse.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimFindAllResponse.java
  backend/src/test/java/mouda/backend/moim/domain/MoimTest.java
Labels: BE, 🌱 기능추가

#311 날짜, 시간 모두 있는 경우만 유효성 검사
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
Labels: BE, 🚑 버그

#310 Input 컴포넌트 스타일 수정
  frontend/src/components/Input/MoimInput.style.ts
Labels: FE, 🚑 버그

#312 모임 수정 페이지 input의 required와 placeHolder 수정
  frontend/src/pages/MoimModifyPage/MoimModifyPage.constant.ts
Labels: FE, 🚑 버그

#314 날짜 api 변경에 대한 대응
  frontend/src/components/MoimCard/MoimCard.style.ts
  frontend/src/components/MoimCard/MoimCard.tsx
  frontend/src/hooks/queries/useMoims.ts
Labels: FE, 🚑 버그

#315 시간 날짜 없으면 다가오는 모임으로 분류
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
Labels: BE, 🚑 버그

#317 모임 생성자 입장에서 취소된 모임 분기 추가
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
Labels: FE, 🌱 기능추가

#319 모임 참여 취소 시, 참여자 목록에 정상적으로 반영되지 않는 문제 수정
  frontend/src/hooks/mutaions/useCancelChamyo.ts
Labels: FE, 🚑 버그

#321 채팅방 띄어쓰기 안되는 버그 수정
  frontend/src/components/ChatBubble/ChatBubble.style.ts
  frontend/src/components/ChatBubble/ChatChildren/ChatChildren.style.tsx
Labels: FE, 🚑 버그

#323 MoimSummary가 좁은 환경에서 버튼이 줄바꿈 되는 현상 수정
  frontend/src/components/MoimSummary/MoimSummary.style.ts
Labels: FE, 🌱 기능추가

#330 nginx 환경 이동 & 도메인 설정에 따른 프론트엔드 배포 스크립트 수정
  .github/workflows/cd-frontend.yml
  .github/workflows/ci-frontend.yml
  frontend/Dockerfile
  frontend/conf.d/default.conf
Labels: FE, 🌱 기능추가, ⚙ 환경설정

#329 채팅컴포넌트 overflow 버그 수정
  frontend/src/components/ChatBubble/ChatBubble.style.ts
  frontend/src/components/ChattingPreview/ChattingPreview.style.ts
  frontend/src/components/ChattingPreview/ChattingPreview.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.stories.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.style.ts
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.tsx
Labels: FE, 🚑 버그

#335 다락방 생성 및 내 다락방 조회 기능 추가
  backend/src/main/java/mouda/backend/darakbang/controller/DarakbangController.java
  backend/src/main/java/mouda/backend/darakbang/controller/DarakbangSwagger.java
  backend/src/main/java/mouda/backend/darakbang/domain/Darakbang.java
  backend/src/main/java/mouda/backend/darakbang/dto/request/DarakbangCreateRequest.java
  backend/src/main/java/mouda/backend/darakbang/dto/response/DarakbangResponse.java
  backend/src/main/java/mouda/backend/darakbang/dto/response/DarakbangResponses.java
  backend/src/main/java/mouda/backend/darakbang/exception/DarakbangErrorMessage.java
  backend/src/main/java/mouda/backend/darakbang/exception/DarakbangException.java
  backend/src/main/java/mouda/backend/darakbang/repository/DarakbangRepository.java
  backend/src/main/java/mouda/backend/darakbang/service/DarakbangService.java
  backend/src/main/java/mouda/backend/darakbang/service/InvitationCodeGenerator.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakBangMemberRole.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/main/java/mouda/backend/darakbangmember/exception/DarakbangMemberErrorMessage.java
  backend/src/main/java/mouda/backend/darakbangmember/exception/DarakbangMemberException.java
  backend/src/main/java/mouda/backend/darakbangmember/repository/repository/DarakbangMemberRepository.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/darakbang/service/DarakbangServiceTest.java
  backend/src/test/java/mouda/backend/darakbang/service/InvitationCodeGeneratorTest.java
  backend/src/test/java/mouda/backend/fixture/DarakbangFixture.java
Labels: BE, 🌱 기능추가

#348 Firebase 연동 후 웹 푸시 알림 구현
  .github/workflows/cicd-backend-dev.yml
  .github/workflows/pr-test.yml
  .gitignore
  backend/build.gradle
  backend/src/main/java/mouda/backend/config/FirebaseConfig.java
  backend/src/main/java/mouda/backend/notification/controller/NotificationController.java
  backend/src/main/java/mouda/backend/notification/controller/NotificationSwagger.java
  backend/src/main/java/mouda/backend/notification/domain/FcmToken.java
  backend/src/main/java/mouda/backend/notification/domain/MemberNotification.java
  backend/src/main/java/mouda/backend/notification/domain/MoudaNotification.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationType.java
  backend/src/main/java/mouda/backend/notification/dto/request/FcmTokenSaveRequest.java
  backend/src/main/java/mouda/backend/notification/exception/NotificationErrorMessage.java
  backend/src/main/java/mouda/backend/notification/exception/NotificationException.java
  backend/src/main/java/mouda/backend/notification/repository/FcmTokenRepository.java
  backend/src/main/java/mouda/backend/notification/repository/MemberNotificationRepository.java
  backend/src/main/java/mouda/backend/notification/repository/MoudaNotificationRepository.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/main/resources/application.yml
Labels: BE, 🌱 기능추가

#343 도메인 url로 변경 후 반영되지 않았던 msw 모킹 url을 수정
  frontend/src/mocks/handler/chatHandler.ts
Labels: FE, 👀 테스트, 🚑 버그

#344 모임어 상태에서 케밥 메뉴의 '모임 삭제하기'를 '모임 취소하기'로 변경, 하드 코딩된 타입 선언
  frontend/src/apis/gets.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/components/Tag/Tag.style.ts
  frontend/src/components/Tag/Tag.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#351 FCM을 이용한 push 알림 구현을 위한 세팅
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/firebase-messaging-sw.js
  frontend/src/apis/posts.ts
  frontend/src/components/LoginForm/LoginForm.tsx
  frontend/src/hooks/mutaions/useServeToken.ts
  frontend/src/index.tsx
  frontend/src/service/forgroundMessage.ts
  frontend/src/service/initFirebase.ts
  frontend/src/service/notification.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
Labels: FE, 🌱 기능추가, ⚙ 환경설정

#352 초대코드 조회, 초대코드 유효성 검사, 다락방 참여 기능
  .github/workflows/cicd-backend-dev.yml
  backend/.gitignore
  backend/src/main/java/mouda/backend/darakbang/controller/DarakbangController.java
  backend/src/main/java/mouda/backend/darakbang/controller/DarakbangSwagger.java
  backend/src/main/java/mouda/backend/darakbang/dto/request/DarakbangEnterRequest.java
  backend/src/main/java/mouda/backend/darakbang/dto/response/CodeValidationResponse.java
  backend/src/main/java/mouda/backend/darakbang/dto/response/InvitationCodeResponse.java
  backend/src/main/java/mouda/backend/darakbang/exception/DarakbangErrorMessage.java
  backend/src/main/java/mouda/backend/darakbang/repository/DarakbangRepository.java
  backend/src/main/java/mouda/backend/darakbang/service/DarakbangService.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/main/java/mouda/backend/darakbangmember/exception/DarakbangMemberErrorMessage.java
  backend/src/main/java/mouda/backend/darakbangmember/repository/repository/DarakbangMemberRepository.java
  backend/src/test/java/mouda/backend/darakbang/service/DarakbangServiceTest.java
  backend/src/test/java/mouda/backend/fixture/DarakbangMemberFixture.java
Labels: BE, 🌱 기능추가

#355 firebase를 서버로 보내는 과정에서 fetch를 post로 수정
  frontend/src/apis/posts.ts
Labels: FE, 🚑 버그

#358 fix: serviceWorker의 register의 경로 수정
  frontend/src/index.tsx
Labels: FE, 🚑 버그

#359 카카오 OAuth 구현
  backend/build.gradle
  backend/src/main/java/mouda/backend/auth/Infrastructure/KakaoOauthClient.java
  backend/src/main/java/mouda/backend/auth/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/controller/AuthSwagger.java
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/auth/service/AuthService.java
  backend/src/main/java/mouda/backend/auth/util/TokenDecoder.java
  backend/src/main/java/mouda/backend/config/RestClientConfig.java
  backend/src/main/java/mouda/backend/config/WebMvcConfig.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/repository/MemberRepository.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/security/JwtProvider.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/mouda/backend/auth/controller/AuthControllerTest.java
  backend/src/test/java/mouda/backend/auth/service/AuthServiceTest.java
  backend/src/test/java/mouda/backend/chamyo/controller/ChamyoControllerTest.java
  backend/src/test/java/mouda/backend/config/JacksonConfigTest.java
  backend/src/test/java/mouda/backend/fixture/TokenFixture.java
  backend/src/test/java/mouda/backend/member/controller/MemberControllerTest.java
  backend/src/test/java/mouda/backend/moim/controller/MoimControllerTest.java
  backend/src/test/java/mouda/backend/please/controller/InterestControllerTest.java
  backend/src/test/java/mouda/backend/please/controller/PleaseControllerTest.java
  backend/src/test/java/mouda/backend/security/JwtProviderTest.java
  backend/src/test/java/mouda/backend/zzim/controller/ZzimControllerTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🌱 기능추가

#356 다락방 멤버 목록 및 권한 조회
  backend/src/main/java/mouda/backend/darakbang/service/DarakbangService.java
  backend/src/main/java/mouda/backend/darakbangmember/controller/DarakbangMemberController.java
  backend/src/main/java/mouda/backend/darakbangmember/controller/DarakbangMemberSwagger.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakBangMemberRole.java
  backend/src/main/java/mouda/backend/darakbangmember/dto/response/DarakbangMemberResponse.java
  backend/src/main/java/mouda/backend/darakbangmember/dto/response/DarakbangMemberResponses.java
  backend/src/main/java/mouda/backend/darakbangmember/dto/response/DarakbangMemberRoleResponse.java
  backend/src/main/java/mouda/backend/darakbangmember/exception/DarakbangMemberErrorMessage.java
  backend/src/main/java/mouda/backend/darakbangmember/repository/repository/DarakbangMemberRepository.java
  backend/src/main/java/mouda/backend/darakbangmember/service/DarakbangMemberService.java
  backend/src/test/java/mouda/backend/darakbangmember/service/DarakbangMemberServiceTest.java
Labels: BE, 🌱 기능추가

#360 알림 기능 적용
  backend/src/main/java/mouda/backend/chamyo/repository/ChamyoRepository.java
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/comment/repository/CommentRepository.java
  backend/src/main/java/mouda/backend/config/FirebaseConfig.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationType.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/mouda/backend/IgnoreNotificationTest.java
  backend/src/test/java/mouda/backend/chamyo/controller/ChamyoControllerTest.java
  backend/src/test/java/mouda/backend/config/JacksonConfigTest.java
  backend/src/test/java/mouda/backend/moim/controller/MoimControllerTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
  backend/src/test/java/mouda/backend/zzim/controller/ZzimControllerTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🌱 기능추가

#362 로그인 kakao o auth
  frontend/src/apis/auth.ts
  frontend/src/components/Icons/KakaoOAuthIcon.tsx
  frontend/src/components/Icons/MainLogoIcon.tsx
  frontend/src/constants/routes.ts
  frontend/src/layouts/LoginLayout/LoginFooter/LoginFooter.style.ts
  frontend/src/layouts/LoginLayout/LoginMain/LoginMain.style.ts
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/KakaoOAuthLoginPage/KakaoOAuthLoginPage.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/routes/ProtectedRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🌱 기능추가

#364 dev 서버 카카오 로그인 버그 이슈 해결
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/mouda/backend/member/domain/MemberTest.java
Labels: BE, 🚑 버그

#367 알림 센터 API 구현
  backend/src/main/java/mouda/backend/notification/controller/NotificationController.java
  backend/src/main/java/mouda/backend/notification/controller/NotificationSwagger.java
  backend/src/main/java/mouda/backend/notification/dto/response/NotificationFindAllResponse.java
  backend/src/main/java/mouda/backend/notification/dto/response/NotificationFindAllResponses.java
  backend/src/main/java/mouda/backend/notification/repository/MemberNotificationRepository.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/test/java/mouda/backend/notification/service/NotificationServiceTest.java
Labels: BE, 🌱 기능추가

#365 serviceWorker의 register의 경로 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/pages/KakaoOAuthLoginPage/KakaoOAuthLoginPage.tsx
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: FE, 🚑 버그, ⚙ 환경설정

#369 헤더에 알림 버튼 추가, 알림 센터 페이지 구현
  frontend/src/apis/endPoints.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/common/assets/notification.svg
  frontend/src/components/MoimTabBar/MoimTabBar.style.ts
  frontend/src/components/NotificationCard/NotificationCard.const.ts
  frontend/src/components/NotificationCard/NotificationCard.style.ts
  frontend/src/components/NotificationCard/NotificationCard.tsx
  frontend/src/components/NotificationList/NotificationList.stories.tsx
  frontend/src/components/NotificationList/NotificationList.style.ts
  frontend/src/components/NotificationList/NotificationList.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/queries/useNotification.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.tsx
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.style.ts
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler/notificationHandler.ts
  frontend/src/pages/MainPage/MainPage.style.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/NotificationPage/NotificationPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#371 알림 클릭 시, 해당 페이지로 이동하는 클릭 이벤트 추가
  frontend/public/firebase-messaging-sw.js
  frontend/src/service/forgroundMessage.ts
Labels: FE, 🌱 기능추가

#373 다락방 관련 ui 및 페이지 구현
  frontend/src/components/ErrorControlledInput/ErrorControlledInput.stories.tsx
  frontend/src/components/ErrorControlledInput/ErrorControlledInput.style.ts
  frontend/src/components/ErrorControlledInput/ErrorControlledInput.tsx
  frontend/src/components/HighlightSpan/HighlightSpan.stories.tsx
  frontend/src/components/HighlightSpan/HighlightSpan.style.ts
  frontend/src/components/HighlightSpan/HighlightSpan.tsx
  frontend/src/components/Icons/SolidArrow.tsx
  frontend/src/components/MemberCard/MemberCard.stories.tsx
  frontend/src/components/MemberCard/MemberCard.style.ts
  frontend/src/components/MemberCard/MemberCard.tsx
  frontend/src/components/MenuItem/MenuItem.stories.tsx
  frontend/src/components/MenuItem/MenuItem.style.tsx
  frontend/src/components/MenuItem/MenuItem.tsx
  frontend/src/components/MenuItemList/MenuItemList.stories.tsx
  frontend/src/components/MenuItemList/MenuItemList.tsx
  frontend/src/components/OptionsPanel/OptionsPanel.stories.tsx
  frontend/src/components/OptionsPanel/OptionsPanel.style.ts
  frontend/src/components/OptionsPanel/OptionsPanel.tsx
  frontend/src/components/SelectBar/SelectBar.stories.tsx
  frontend/src/components/SelectBar/SelectBar.style.ts
  frontend/src/components/SelectBar/SelectBar.tsx
  frontend/src/constants/poclies.ts
  frontend/src/constants/routes.ts
  frontend/src/layouts/SelectLayout/SelectBottomWrapper/SelectBottomWrapper.style.ts
  frontend/src/layouts/SelectLayout/SelectBottomWrapper/SelectBottomWrapper.tsx
  frontend/src/layouts/SelectLayout/SelectContentContainer/SelectContentContainer.stories.tsx
  frontend/src/layouts/SelectLayout/SelectContentContainer/SelectContentContainer.style.ts
  frontend/src/layouts/SelectLayout/SelectContentContainer/SelectContentContainer.tsx
  frontend/src/layouts/SelectLayout/SelectLayout.style.ts
  frontend/src/layouts/SelectLayout/SelectLayout.tsx
  frontend/src/layouts/StretchContentLayout/StretchContentBottomWrapper/StretchContentBottomWrapper.style.ts
  frontend/src/layouts/StretchContentLayout/StretchContentBottomWrapper/StretchContentBottomWrapper.tsx
  frontend/src/layouts/StretchContentLayout/StretchContentContainer/StretchContentContainer.style.ts
  frontend/src/layouts/StretchContentLayout/StretchContentContainer/StretchContentContainer.tsx
  frontend/src/layouts/StretchContentLayout/StretchContentLayout.style.ts
  frontend/src/layouts/StretchContentLayout/StretchContentLayout.tsx
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.tsx
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationPage.style.ts
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/DarakbangEntrancePage/DarakbangEntrancePage.tsx
  frontend/src/pages/DarakbangInvitationPage/DarakbangInvitationPage.style.ts
  frontend/src/pages/DarakbangInvitationPage/DarakbangInvitationPage.tsx
  frontend/src/pages/DarakbangLandingPage/DarakbangLandingPage.tsx
  frontend/src/pages/DarakbangManagementPage/DarakbangManagementPage.tsx
  frontend/src/pages/DarakbangMembersPage/DarakbangMembersPage.style.tsx
  frontend/src/pages/DarakbangMembersPage/DarakbangMembersPage.tsx
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknameModalContent/DarakbangNicknameModalContent.style.ts
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknameModalContent/DarakbangNicknameModalContent.tsx
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknamePage.tsx
  frontend/src/pages/DarakbangSelectOptionPage/DarakbangSelectOptionPage.tsx
  frontend/src/pages/DarakbangSelectPage/DarakbangSelectPage.style.ts
  frontend/src/pages/DarakbangSelectPage/DarakbangSelectPage.tsx
  frontend/src/routes/DarakbangInvitationRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🌱 기능추가

#379 다락방 api를 페이지에 연결
  frontend/.gitignore
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/components/OptionsPanel/OptionsPanel.stories.tsx
  frontend/src/components/OptionsPanel/OptionsPanel.style.ts
  frontend/src/components/OptionsPanel/OptionsPanel.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/mutaions/useCreateDarakbang.ts
  frontend/src/hooks/mutaions/useEnterDarakbang.ts
  frontend/src/hooks/queries/useDarakbangInviteCode.ts
  frontend/src/hooks/queries/useDarakbangMembers.ts
  frontend/src/hooks/queries/useDarakbangNameByCode.ts
  frontend/src/hooks/queries/useMyDarakbang.ts
  frontend/src/hooks/queries/useMyDarakbangRole.ts
  frontend/src/layouts/CompleteLayout/CompleteBottomWrapper/CompleteBottomWrapper.style.ts
  frontend/src/layouts/SelectLayout/SelectContentContainer/SelectContentContainer.style.ts
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationModalContent/DarakbangCreationModalContent.style.ts
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationModalContent/DarakbangCreationModalContent.tsx
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/DarakbangEntrancePage/DarakbangEntrancePage.tsx
  frontend/src/pages/DarakbangInvitationPage/DarakbangInvitationPage.tsx
  frontend/src/pages/DarakbangMembersPage/DarakbangMembersPage.tsx
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknamePage.tsx
  frontend/src/pages/DarakbangSelectPage/DarakbangSelectPage.tsx
  frontend/src/pages/KakaoOAuthLoginPage/KakaoOAuthLoginPage.tsx
  frontend/src/pages/MainPage/MainPage.style.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/queryClient.ts
  frontend/src/routes/DarakbangInvitationRoute.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#375 알림 기능 오류 수정
  backend/src/main/java/mouda/backend/config/CorsConfig.java
  backend/src/main/java/mouda/backend/notification/domain/MoudaNotification.java
  backend/src/main/java/mouda/backend/notification/dto/response/NotificationFindAllResponse.java
  backend/src/main/java/mouda/backend/notification/repository/FcmTokenRepository.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/mouda/backend/notification/service/NotificationServiceTest.java
Labels: BE, 🚑 버그

#372 데이터베이스 클리너 로직 개선
  backend/build.gradle
  backend/src/test/java/mouda/backend/chat/repository/ChatRepositoryTest.java
  backend/src/test/java/mouda/backend/chat/service/ChatServiceTest.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/config/NoTransactionExtension.java
  backend/src/test/java/mouda/backend/darakbang/service/DarakbangServiceTest.java
  backend/src/test/java/mouda/backend/darakbangmember/service/DarakbangMemberServiceTest.java
  backend/src/test/java/mouda/backend/member/repository/MemberRepositoryTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
  backend/src/test/java/mouda/backend/please/service/PleaseServiceTest.java
  backend/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  backend/src/test/resources/junit-platform.properties
Labels: BE, ⚒️ 리팩터링, 👀 테스트

#389 알림에 다락방 기능 반영
  backend/src/main/java/mouda/backend/chamyo/repository/ChamyoRepository.java
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/comment/repository/CommentRepository.java
  backend/src/main/java/mouda/backend/config/FirebaseConfig.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/notification/controller/NotificationController.java
  backend/src/main/java/mouda/backend/notification/controller/NotificationSwagger.java
  backend/src/main/java/mouda/backend/notification/domain/MemberNotification.java
  backend/src/main/java/mouda/backend/notification/repository/MemberNotificationRepository.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/test/java/mouda/backend/IgnoreNotificationTest.java
  backend/src/test/java/mouda/backend/chat/service/ChatServiceTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
  backend/src/test/java/mouda/backend/notification/service/NotificationServiceTest.java
Labels: BE, ⚒️ 리팩터링

#382 e2e테스트를 위한 cypress 도입
  frontend/.eslintrc.cjs
  frontend/cypress.config.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/package-lock.json
  frontend/package.json
Labels: FE, ⚙ 환경설정

#384 ci에서 캐싱된 npm을 가져오는 설정 추가
  .github/workflows/ci-frontend.yml
Labels: FE, ⚙ 환경설정

#390 다락방에 종속된 api를 연결
  frontend/src/apis/apiClient.ts
  frontend/src/apis/deletes.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/patches.ts
  frontend/src/apis/posts.ts
  frontend/src/common/lastDarakbangManager.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/mutaions/useAddMoim.ts
  frontend/src/hooks/mutaions/useAddPlease.ts
  frontend/src/hooks/mutaions/useCancelChamyo.ts
  frontend/src/hooks/mutaions/useCancelMoim.ts
  frontend/src/hooks/mutaions/useChangeZzim.ts
  frontend/src/hooks/mutaions/useCompleteMoin.ts
  frontend/src/hooks/mutaions/useInterest.ts
  frontend/src/hooks/mutaions/useJoinMoim.ts
  frontend/src/hooks/mutaions/useModifyMoim.ts
  frontend/src/hooks/mutaions/useReopenMoim.ts
  frontend/src/hooks/mutaions/useWriteComment.ts
  frontend/src/hooks/queries/useChamyoAll.ts
  frontend/src/hooks/queries/useChamyoMine.ts
  frontend/src/hooks/queries/useChatPreiview.ts
  frontend/src/hooks/queries/useChats.test.tsx
  frontend/src/hooks/queries/useChats.ts
  frontend/src/hooks/queries/useDarakbangInviteCode.ts
  frontend/src/hooks/queries/useDarakbangMembers.ts
  frontend/src/hooks/queries/useMoim.ts
  frontend/src/hooks/queries/useMoims.ts
  frontend/src/hooks/queries/useMyDarakbangRole.ts
  frontend/src/hooks/queries/useMyInfo.ts
  frontend/src/hooks/queries/useMyMoim.ts
  frontend/src/hooks/queries/useMyMoims.ts
  frontend/src/hooks/queries/useMyZzimMoim.ts
  frontend/src/hooks/queries/useNotification.ts
  frontend/src/hooks/queries/usePleases.ts
  frontend/src/hooks/queries/useZzimMine.ts
  frontend/src/mocks/handler/chatHandler.ts
  frontend/src/pages/DarakbangInvitationPage/DarakbangInvitationPage.tsx
  frontend/src/pages/DarakbangMembersPage/DarakbangMembersPage.tsx
  frontend/src/pages/DarakbangSelectPage/DarakbangSelectPage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
Labels: FE, 🌱 기능추가

#393 알림 센터에서 알림 클릭 시, 해당 정보와 관련된 페이지로 이동
  frontend/.storybook/main.ts
  frontend/src/components/NotificationCard/NotificationCard.style.ts
  frontend/src/components/NotificationCard/NotificationCard.tsx
  frontend/src/components/NotificationList/NotificationList.stories.tsx
  frontend/src/components/NotificationList/NotificationList.tsx
  frontend/src/types/index.d.ts
  frontend/src/utils/formatters.ts
Labels: FE, 🌱 기능추가

#400 프로덕션 서버와 데이터베이스 구축
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: BE, ⚙ 환경설정

#392 다락방 관련 API 추가 및 다락방 모임/해주세요 검증 AOP 제거
  backend/build.gradle
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/auth/service/AuthService.java
  backend/src/main/java/mouda/backend/chamyo/domain/Chamyo.java
  backend/src/main/java/mouda/backend/chamyo/dto/response/ChamyoFindAllResponse.java
  backend/src/main/java/mouda/backend/chamyo/exception/ChamyoErrorMessage.java
  backend/src/main/java/mouda/backend/chamyo/repository/ChamyoRepository.java
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
  backend/src/main/java/mouda/backend/chat/dto/request/ChatCreateRequest.java
  backend/src/main/java/mouda/backend/chat/dto/request/DateTimeConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/dto/request/PlaceConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/dto/response/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/chat/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/comment/domain/Comment.java
  backend/src/main/java/mouda/backend/comment/dto/request/CommentCreateRequest.java
  backend/src/main/java/mouda/backend/comment/repository/CommentRepository.java
  backend/src/main/java/mouda/backend/common/RequiredDarakbangAspect.java
  backend/src/main/java/mouda/backend/common/RequiredDarakbangMoim.java
  backend/src/main/java/mouda/backend/common/RequiredDarakbangPlease.java
  backend/src/main/java/mouda/backend/darakbang/controller/DarakbangController.java
  backend/src/main/java/mouda/backend/darakbang/controller/DarakbangSwagger.java
  backend/src/main/java/mouda/backend/darakbang/dto/request/DarakbangEnterRequest.java
  backend/src/main/java/mouda/backend/darakbang/dto/response/CodeValidationResponse.java
  backend/src/main/java/mouda/backend/darakbang/dto/response/DarakbangNameResponse.java
  backend/src/main/java/mouda/backend/darakbang/service/DarakbangService.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/main/java/mouda/backend/darakbangmember/dto/response/DarakbangMemberResponse.java
  backend/src/main/java/mouda/backend/member/service/MemberService.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/please/controller/InterestController.java
  backend/src/main/java/mouda/backend/please/domain/Interest.java
  backend/src/main/java/mouda/backend/please/domain/Please.java
  backend/src/main/java/mouda/backend/please/exception/PleaseErrorMessage.java
  backend/src/main/java/mouda/backend/please/repository/InterestRepository.java
  backend/src/main/java/mouda/backend/please/service/InterestService.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/main/java/mouda/backend/zzim/domain/Zzim.java
  backend/src/main/java/mouda/backend/zzim/exception/ZzimErrorMessage.java
  backend/src/main/java/mouda/backend/zzim/repository/ZzimRepository.java
  backend/src/main/java/mouda/backend/zzim/service/ZzimService.java
  backend/src/test/java/mouda/backend/chat/service/ChatServiceTest.java
  backend/src/test/java/mouda/backend/comment/domain/CommentTest.java
  backend/src/test/java/mouda/backend/fixture/ChatFixture.java
  backend/src/test/java/mouda/backend/fixture/CommentFixture.java
  backend/src/test/java/mouda/backend/fixture/DarakbangMemberFixture.java
  backend/src/test/java/mouda/backend/notification/service/NotificationServiceTest.java
  backend/src/test/java/mouda/backend/please/service/PleaseServiceTest.java
Labels: BE, 🌱 기능추가

#397 모임 만들기 Funnel UI 적용
  frontend/src/components/BackArrowButton/BackArrowButton.style.ts
  frontend/src/components/BackArrowButton/BackArrowButton.tsx
  frontend/src/components/Funnel/FunnelButton/FunnelButton.tsx
  frontend/src/components/Funnel/FunnelInput/FunnelInput.stories.tsx
  frontend/src/components/Funnel/FunnelInput/FunnelInput.style.ts
  frontend/src/components/Funnel/FunnelInput/FunnelInput.tsx
  frontend/src/components/Funnel/FunnelQuestion/FunnelQuestion.stories.tsx
  frontend/src/components/Funnel/FunnelQuestion/FunnelQuestion.tsx
  frontend/src/components/Funnel/FunnelQuestion/FunnelQuestionHighlight/FunnelQuestionHighlight.style.ts
  frontend/src/components/Funnel/FunnelQuestion/FunnelQuestionHighlight/FunnelQuestionHighlight.tsx
  frontend/src/components/Funnel/FunnelQuestion/FunnelQuestionText/FunnelQuestionText.tsx
  frontend/src/components/Funnel/FunnelRadioCardGroup/FunnelRadioCardGroup.style.ts
  frontend/src/components/Funnel/FunnelRadioCardGroup/FunnelRadioCardGroup.tsx
  frontend/src/components/Funnel/FunnelRadioCardGroup/FunnelRadioCardGroupOption/FunnelRadioCardGroupOption.style.ts
  frontend/src/components/Funnel/FunnelRadioCardGroup/FunnelRadioCardGroupOption/FunnelRadioCardGroupOption.tsx
  frontend/src/components/Funnel/FunnelStepIndicator/FunnelStepIndicator.stories.tsx
  frontend/src/components/Funnel/FunnelStepIndicator/FunnelStepIndicator.style.ts
  frontend/src/components/Funnel/FunnelStepIndicator/FunnelStepIndicator.tsx
  frontend/src/components/Funnel/FunnelTextArea/FunnelTextArea.style.ts
  frontend/src/components/Funnel/FunnelTextArea/FunnelTextArea.tsx
  frontend/src/components/Icons/BackArrowIcon.tsx
  frontend/src/components/Icons/SelectionIcon.tsx
  frontend/src/hooks/useFunnel.test.tsx
  frontend/src/hooks/useFunnel.ts
  frontend/src/hooks/useStatePersist.test.tsx
  frontend/src/hooks/useStatePersist.ts
  frontend/src/layouts/FunnelLayout/FunnelFooter/FunnelFooter.style.ts
  frontend/src/layouts/FunnelLayout/FunnelFooter/FunnelFooter.tsx
  frontend/src/layouts/FunnelLayout/FunnelLayout.style.ts
  frontend/src/layouts/FunnelLayout/FunnelLayout.tsx
  frontend/src/layouts/FunnelLayout/FunnelMain/FunnelMain.style.ts
  frontend/src/layouts/FunnelLayout/FunnelMain/FunnelMain.tsx
  frontend/src/pages/MoimCreationPage/MoimCreatePage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.constant.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.hook.test.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.util.test.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.util.ts
  frontend/src/pages/MoimCreationPage/Steps/DateAndTimeStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/DescriptionStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/MaxPeopleStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/OfflineOrOnlineStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/PlaceStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/TitleStep.tsx
  frontend/src/pages/MoimCreationPage/useMoimInfoInput.test.tsx
Labels: FE, 🌱 기능추가

#403 PWA 이용을 위한 manifest.json 작성
  frontend/public/android/android-launchericon-144-144.png
  frontend/public/android/android-launchericon-192-192.png
  frontend/public/android/android-launchericon-48-48.png
  frontend/public/android/android-launchericon-512-512.png
  frontend/public/android/android-launchericon-72-72.png
  frontend/public/android/android-launchericon-96-96.png
  frontend/public/manifest.json
  frontend/src/apis/posts.ts
  frontend/src/components/LoginForm/LoginForm.tsx
  frontend/src/index.html
  frontend/src/index.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/service/forgroundMessage.ts
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: FE, ⚙ 환경설정

#406 프론트에서 darakbang URL 구현
  frontend/src/App.tsx
  frontend/src/apis/posts.ts
  frontend/src/common/getRoutes.ts
  frontend/src/common/inviteCodeManager.tsx
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/components/NavigationBar/NavigationBar.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useCreateDarakbang.ts
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/DarakbangEntrancePage/DarakbangEntrancePage.tsx
  frontend/src/pages/DarakbangManagementPage/DarakbangManagementPage.tsx
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknamePage.tsx
  frontend/src/pages/DarakbangSelectPage/DarakbangSelectPage.tsx
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/KakaoOAuthLoginPage/KakaoOAuthLoginPage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/MoimModifyPage/MoimModifyPage.tsx
  frontend/src/pages/NotificationPage/NotificationPage.tsx
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.tsx
  frontend/src/pages/PleasePage/PleasePage.tsx
  frontend/src/routes/DarakbangInvitationRoute.tsx
  frontend/src/routes/SlashRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🌱 기능추가

#396 FCM 토큰을 서버 내에서 최신 상태로 유지하기 위한 기능 구현
  backend/.DS_Store
  backend/src/main/java/mouda/backend/BackendApplication.java
  backend/src/main/java/mouda/backend/notification/controller/NotificationSwagger.java
  backend/src/main/java/mouda/backend/notification/domain/FcmToken.java
  backend/src/main/java/mouda/backend/notification/exception/NotificationErrorMessage.java
  backend/src/main/java/mouda/backend/notification/repository/FcmTokenRepository.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/test/java/mouda/backend/chamyo/controller/ChamyoControllerTest.java
Labels: BE, 🌱 기능추가

#411 모우다 HTML 메타 태그 작성
  frontend/public/main-logo.png
  frontend/public/main-logo2.png
  frontend/src/index.html
  frontend/src/pages/MoimCreationPage/MoimCreationPage.hook.ts
Labels: FE, 🌱 기능추가

#410 api 에러를 컨트롤 하는 페이지를 구현한다
  frontend/src/routes/ErrorRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🌱 기능추가

#402 참여하지 않은 경우 예외 던지는 로직 제거
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/please/domain/Please.java
  backend/src/main/java/mouda/backend/please/service/InterestService.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/main/java/mouda/backend/zzim/service/ZzimService.java
Labels: BE, 🚑 버그

#416 참여한 모임의 채팅 조회 안되는 오류 수정
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
Labels: BE, 🚑 버그

#422 qa에서 나온 버그 수정
  frontend/src/apis/apiClient.ts
  frontend/src/apis/auth.ts
  frontend/src/apis/deletes.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/patches.ts
  frontend/src/apis/posts.ts
  frontend/src/common/getRoutes.ts
  frontend/src/components/MineInfoCard/MineInfoCard.tsx
  frontend/src/components/NavigationBar/NavigationBar.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/queries/useNowDarakbangNameById.ts
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/DarakbangInvitationPage/DarakbangInvitationPage.tsx
  frontend/src/pages/DarakbangLandingPage/DarakbangLandingPage.tsx
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknamePage.tsx
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/PleasePage/PleasePage.tsx
  frontend/src/routes/DarakbangInvitationRoute.tsx
  frontend/src/routes/ProtectedRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🚑 버그

#417 알림 카드 클릭 이벤트 연결
  frontend/src/components/NotificationCard/NotificationCard.tsx
Labels: FE, 🚑 버그

#427 요청 로깅 기능에서 예외 발생시 로깅 누락 이슈 해결
  backend/src/main/java/mouda/backend/aop/logging/RequestLoggingAspect.java
  backend/src/main/java/mouda/backend/config/WebMvcConfig.java
  backend/src/main/java/mouda/backend/config/interceptor/ApiRequestLoggingInterceptor.java
Labels: BE, ⚒️ 리팩터링

#444 프로덕션 배포 환경 수정
  .gitignore
  backend/.gitignore
Labels: BE, FE, ⚙ 환경설정

#440 다락방 초대링크 입력해서 들어가는 경우 내 다락방으로 제대로 가지지 않는 버그 수정
  frontend/src/apis/posts.ts
  frontend/src/hooks/mutaions/useEnterDarakbang.ts
  frontend/src/routes/DarakbangInvitationRoute.tsx
Labels: FE, 🚑 버그

#443 백그라운드 알림이 undefined로 오는 문제를 수정
  frontend/public/firebase-messaging-sw.js
Labels: FE, 🚑 버그

#441 폴링 방식으로 보낸 채팅 요청이 모두 로그에 찍히는 현상 해결
  backend/src/main/java/mouda/backend/aop/logging/ExceptRequestLogging.java
  backend/src/main/java/mouda/backend/aop/logging/RequestLoggingAspect.java
  backend/src/main/java/mouda/backend/chat/controller/ChatController.java
Labels: BE, ⚒️ 리팩터링

#452 모임만들기 UI UX 문제 해결
  frontend/src/components/Funnel/FunnelInput/FunnelInput.tsx
  frontend/src/components/Funnel/FunnelTextArea/FunnelTextArea.tsx
  frontend/src/layouts/FunnelLayout/FunnelFooter/FunnelFooter.style.ts
  frontend/src/layouts/FunnelLayout/FunnelFooter/FunnelFooter.tsx
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.style.ts
  frontend/src/pages/MoimCreationPage/Steps/DescriptionStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/MaxPeopleStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/PlaceStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/TitleStep.tsx
Labels: FE, 🚑 버그

#457 모임, 해주세요, 알림 정렬 추가
  backend/src/main/java/mouda/backend/chamyo/repository/ChamyoRepository.java
  backend/src/main/java/mouda/backend/moim/repository/MoimRepository.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/java/mouda/backend/notification/repository/MemberNotificationRepository.java
  backend/src/main/java/mouda/backend/notification/service/NotificationService.java
  backend/src/main/java/mouda/backend/please/repository/PleaseRepository.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/main/java/mouda/backend/zzim/repository/ZzimRepository.java
  backend/src/test/java/mouda/backend/notification/service/NotificationServiceTest.java
  backend/src/test/java/mouda/backend/please/service/PleaseServiceTest.java
Labels: BE, 🌱 기능추가

#451 케밥 메뉴의 폰트 크기를 변경
  frontend/src/components/KebabMenu/KebabMenu.style.ts
Labels: FE, 👻 사소한 수정

#459 URL로 다락방, 모임 접근시 예외 처리
  frontend/src/queryClient.ts
Labels: FE, 🚑 버그

#456 다락방 초대인 경우 로그인 만료된 토큰 에러 처리
  frontend/src/apis/gets.ts
Labels: FE, 🚑 버그

#462 모임 만들기 맞지막 스탭 포커싱
  frontend/src/components/Funnel/FunnelTextArea/FunnelTextArea.tsx
  frontend/src/pages/MoimCreationPage/Steps/DescriptionStep.tsx
Labels: FE, 🌱 기능추가

#465 다락방 이름이 길어질 때에 생기는 UI 문제를 해결한다
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.style.ts
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.tsx
  frontend/src/components/OptionsPanel/OptionsPanel.style.ts
  frontend/src/components/OptionsPanel/OptionsPanel.tsx
  frontend/src/constants/poclies.ts
  frontend/src/pages/ChatPage/ChatPage.tsx
  frontend/src/pages/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/DarakbangLandingPage/DarakbangLandingPage.tsx
  frontend/src/pages/DarakbangNicknamePage/DarakbangNicknamePage.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/PleasePage/PleasePage.tsx
Labels: FE, 🚑 버그

#469 모바일을 위한 Meta 태그 추가구현
  frontend/public/android/android-launchericon-144-144.png
  frontend/public/android/android-launchericon-192-192.png
  frontend/public/android/android-launchericon-48-48.png
  frontend/public/android/android-launchericon-512-512.png
  frontend/public/android/android-launchericon-72-72.png
  frontend/public/android/android-launchericon-96-96.png
  frontend/public/preview-image.png
  frontend/src/index.html
Labels: FE, 🌱 기능추가

#472 알림 카드 클릭 시, url이동하는 기능 수정, 알림 2번 오는 기능 수정
  frontend/public/firebase-messaging-sw.js
  frontend/src/components/NotificationList/NotificationList.tsx
Labels: FE, 🚑 버그

#473 스켈레톤 요소 컴포넌트
  frontend/src/components/Skeleton/SkeletonPiece.stories.tsx
  frontend/src/components/Skeleton/SkeletonPiece.style.ts
  frontend/src/components/Skeleton/SkeletonPiece.tsx
Labels: FE, 🌱 기능추가

#477 댓글 작성한 사람에게 알림이 가는 오류 수정
  .github/workflows/cicd-backend-dev.yml
  backend/src/main/java/mouda/backend/comment/repository/CommentRepository.java
Labels: BE, 🚑 버그

#467 같은 다락방 참여자에게만 모임 생성 알림이 전송되도록 수정
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
Labels: BE, 🚑 버그

#481 알림에 대한 권한을 미 설정시, 알림에 대한 설명을 모달로 표시
  frontend/src/pages/KakaoOAuthLoginPage/KakaoOAuthLoginPage.tsx
  frontend/src/pages/MainPage/MainPage.style.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/NotificationPage/NotificationPage.style.ts
  frontend/src/pages/NotificationPage/NotificationPage.tsx
Labels: FE, 🌱 기능추가

#483 목록 로딩 스켈레톤 UI 구현
  frontend/src/components/MoimList/MoimCardListSkeleton/MoimCardListSkeleton.style.ts
  frontend/src/components/MoimList/MoimCardListSkeleton/MoimCardListSkeleton.tsx
  frontend/src/components/MoimList/MoimCardListSkeleton/MoimCardSkeleton/MoimCardSkeleton.stories.tsx
  frontend/src/components/MoimList/MoimCardListSkeleton/MoimCardSkeleton/MoimCardSkeleton.style.ts
  frontend/src/components/MoimList/MoimCardListSkeleton/MoimCardSkeleton/MoimCardSkeleton.tsx
  frontend/src/components/MoimList/MoimList.tsx
  frontend/src/components/PleaseList/PleaseCardListSkeleton/PleaseCardListSkeleton.style.ts
  frontend/src/components/PleaseList/PleaseCardListSkeleton/PleaseCardListSkeleton.tsx
  frontend/src/components/PleaseList/PleaseCardListSkeleton/PleaseCardSkeleton/PleaseCardSkeleton.stories.tsx
  frontend/src/components/PleaseList/PleaseCardListSkeleton/PleaseCardSkeleton/PleaseCardSkeleton.style.ts
  frontend/src/components/PleaseList/PleaseCardListSkeleton/PleaseCardSkeleton/PleaseCardSkeleton.tsx
  frontend/src/components/PleaseList/PleaseList.tsx
  frontend/src/pages/ChatPage/ChatListSkeleton/ChatCardListSkeleton.style.ts
  frontend/src/pages/ChatPage/ChatListSkeleton/ChatCardListSkeleton.tsx
  frontend/src/pages/ChatPage/ChatListSkeleton/ChatCardSkeleton/ChatCardSkeleton.stories.tsx
  frontend/src/pages/ChatPage/ChatListSkeleton/ChatCardSkeleton/ChatCardSkeleton.style.ts
  frontend/src/pages/ChatPage/ChatListSkeleton/ChatCardSkeleton/ChatCardSkeleton.tsx
  frontend/src/pages/ChatPage/ChatPage.tsx
Labels: FE, 🌱 기능추가

#485 모임 상세페이지 스켈레톤 구현
  frontend/src/components/CommentCard/CommentCardSkeleton.tsx
  frontend/src/components/CommentList/CommentListSkeleton.tsx
  frontend/src/components/MoimDescription/MoimDescriptionSkeleton.tsx
  frontend/src/components/MoimInformation/MoimInfomationSkeleton.tsx
  frontend/src/components/MoimSummary/MoimSummarySkeleton.tsx
  frontend/src/components/ProfileList/ProfileListSkeleton.tsx
  frontend/src/components/Tag/TagSkeleton.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
Labels: FE, 🌱 기능추가

#489 알림 허욜 모달 UI 문제 해결 (임시방편)
  frontend/src/pages/MainPage/MainPage.style.ts
  frontend/src/pages/MainPage/MainPage.tsx
Labels: FE, 🚑 버그

#487 댓글 알림 대상 수정
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
Labels: BE, 🚑 버그

#494 UI 문제 해결 (모달 깨지는 문제, 모임 만들기 인풋 자동 포커싱)
  frontend/src/index.html
  frontend/src/pages/MoimCreationPage/Steps/DescriptionStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/MaxPeopleStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/PlaceStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/TitleStep.tsx
  frontend/src/pages/NotificationPage/NotificationPage.style.ts
Labels: FE, 🚑 버그

#497 Develop frontend
  frontend/src/index.html
  frontend/src/pages/MoimCreationPage/Steps/DescriptionStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/MaxPeopleStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/PlaceStep.tsx
  frontend/src/pages/MoimCreationPage/Steps/TitleStep.tsx
  frontend/src/pages/NotificationPage/NotificationPage.style.ts
Labels: FE, 🚑 버그

#500 채팅방 및 해주세요 페이지 정렬 추가
  backend/src/main/java/mouda/backend/chat/service/ChatService.java
  backend/src/main/java/mouda/backend/please/service/PleaseService.java
  backend/src/test/java/mouda/backend/chat/service/ChatServiceTest.java
  backend/src/test/java/mouda/backend/please/service/PleaseServiceTest.java
Labels: BE, 🌱 기능추가

#506 Swagger-ui에서의 CORS 에러 해결
  backend/src/main/resources/application.yml
Labels: BE, 🚑 버그

#507 같은 회원이 연속 참여 버튼을 눌렀을 때 생기는 동시성 문제 해결
  backend/hs_err_pid19740.log
  backend/hs_err_pid20488.log
  backend/hs_err_pid20992.log
  backend/replay_pid19740.log
  backend/replay_pid20488.log
  backend/replay_pid20992.log
  backend/src/main/java/mouda/backend/chamyo/service/ChamyoService.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/repository/MoimRepository.java
  backend/src/test/java/mouda/backend/chamyo/service/ChamyoServiceTest.java
Labels: BE, 🚑 버그

#502 모임을 만들 때 이전 시간를 지정하면 그 창은 넘어가지는 문제 수정
  frontend/src/pages/MoimCreationPage/MoimCreationPage.util.test.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.util.ts
  frontend/src/queryClient.ts
Labels: FE, 🌱 기능추가

#504 알림 센터 페이지 Skeleton UI 구현, 알림이 없을 시, 문구 표시
  frontend/src/components/NotificationCard/NotificationCardSkeleton/NotificationCardSkeleton.stories.tsx
  frontend/src/components/NotificationCard/NotificationCardSkeleton/NotificationCardSkeleton.style.ts
  frontend/src/components/NotificationCard/NotificationCardSkeleton/NotificationCardSkeleton.tsx
  frontend/src/components/NotificationList/NotificationList.tsx
  frontend/src/components/NotificationList/NotificationListSkeleton/NotificationListSkeleton.stories.tsx
  frontend/src/components/NotificationList/NotificationListSkeleton/NotificationListSkeleton.tsx
  frontend/src/pages/NotificationPage/NotificationPage.tsx
Labels: FE, 🌱 기능추가
