Repository woowacourse-teams/2024-mouda, pull requests merged in 2024-11, with the labels that each got.

#787 초대코드 로직 수정, 알림이 사파리에서 작동하지 않는 문제 수정
  frontend/src/App.tsx
  frontend/src/components/OptionsPanel/OptionsPanel.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Navigator/DarakbangInvitationRoute.tsx
  frontend/src/service/forgroundMessage.ts
  frontend/src/service/initFirebase.ts
  frontend/src/service/notification.ts
  frontend/src/utils/checkCanUseFirebase.ts
Labels: FE, 🚑 버그

#796 다락방 별 모임을 조회하는 API의 요청 응답 속도 개선
  backend/src/main/java/mouda/backend/moim/implement/finder/MoimFinder.java
  backend/src/main/java/mouda/backend/moim/infrastructure/ChamyoRepository.java
  backend/src/main/java/mouda/backend/moim/infrastructure/ZzimRepository.java
  backend/src/main/java/mouda/backend/moim/infrastructure/dto/ChamyoCountResponse.java
Labels: BE, ⚒️ 리팩터링

#794 무중단배포 중단 문제 해결
  .github/workflows/be-rolling-deploy.yml
  backend/src/main/java/mouda/backend/common/HealthCheckController.java
  backend/src/main/resources/application-prod.yml
Labels: BE, ⚙ 환경설정
