Repository woowacourse-teams/2024-mouda, pull requests merged in 2024-07, with the labels that each got.

#3 Chore/#2 백엔드 초기 환경 설정
  backend/.gitignore
  backend/HELP.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/mouda/backend/BackendApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/mouda/backend/BackendApplicationTests.java
Labels: BE, ⚙환경설정

#7 chore: 기본 환경설정 추가
  babel.config.json
  frontend/.browserslistrc
  frontend/.eslintrc.cjs
  frontend/.stylelintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/button.styles.ts
Labels: FE, ⚙ 환경설정

#9 chore: 초기설정 수정
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: FE, ⚙ 환경설정

#10 chore:바벨 설정 파일 위치 변경
  frontend/babel.config.json
Labels: FE, ⚙ 환경설정

#16 Feat/#14: api 요청 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/env.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/mutaions/useAddMoim.ts
  frontend/src/queries/useMoim.ts
  frontend/src/queryKeys.ts
  frontend/src/types/requests.d.ts
Labels: FE, 🌱 기능추가

#17 [Feature/#15] 모임 생성 및 조회 기능 구현
  backend/src/main/java/mouda/backend/common/ApiResponse.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimFindAllResponse.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimFindAllResponses.java
  backend/src/main/java/mouda/backend/moim/repository/MoimRepository.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 🌱 기능추가

#18 Feature/#12
  frontend/src/App.tsx
  frontend/src/common/reset.style.ts
  frontend/src/layouts/MoimList/MoimList.style.ts
  frontend/src/layouts/MoimList/MoimList.tsx
  frontend/src/layouts/MoimList/mockData.ts
  frontend/src/layouts/MoimRegister/BackArrowLogo.tsx
  frontend/src/layouts/MoimRegister/MoimRegister.style.ts
  frontend/src/layouts/MoimRegister/MoimRegister.tsx
  frontend/src/layouts/MoimRegister/icon_regular.svg
Labels: FE, 🌱 기능추가

#20 Feat/#13
  frontend/src/App.tsx
  frontend/src/common/assets/index.ts
  frontend/src/common/assets/plus.svg
  frontend/src/common/common.style.ts
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/Button.type.ts
  frontend/src/components/Card/MoimCard.style.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/components/Card/MoimCard.type.ts
  frontend/src/components/Input/MoimInput.style.ts
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/components/Input/MoimInput.type.ts
  frontend/src/components/MoimCardList/MoimCardList.style.ts
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/components/MoimCardList/MoimCardList.type.ts
  frontend/src/constants/index.ts
  frontend/src/custom.d.ts
  frontend/src/reset.ts
  frontend/src/type/index.ts
Labels: FE, 🌱 기능추가

#27 style: Button 컴포넌트 active 스타일 추가
  frontend/src/App.tsx
  frontend/src/common/assets/index.ts
  frontend/src/common/assets/plus.svg
  frontend/src/common/assets/tabler_plus.svg
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
Labels: FE, 🌱 기능추가

#28 feat/#21 수정한 api에 맞게 타입을 수정
  frontend/src/queries/useMoims.ts
  frontend/src/types/requests.d.ts
Labels: FE, 🌱 기능추가

#34 [Fix/#33] Cors 문제 해결
  backend/src/main/java/mouda/backend/config/CorsConfig.java
Labels: BE, 🚑 버그

#39 [Refactor/#38] data.sql 모임 데이터 개수 수정
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
Labels: BE, ⚒️ 리팩터링

#47 Feature/#41 부족했던 fe 기능 추가
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/Button.type.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/pages/MoimList.tsx
  frontend/src/pages/MoimRegister.tsx
  frontend/src/queries/useMoims.ts
  frontend/src/utils/formatters.ts
Labels: FE, 🌱 기능추가

#53 CI/CD 구축
  .github/workflows/cd-dev.yml
  .github/workflows/ci-dev.yml
  backend/Dockerfile
  backend/docker-compose.yml
Labels: BE, ⚙ 환경설정

#61 모임 참여 기능 구현
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimJoinRequest.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 🌱 기능추가

#64 2-1 스프린트 전체 리팩토링
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/endPoints.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/button.styles.ts
  frontend/src/common/assets/back.svg
  frontend/src/common/reset.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/Button.type.ts
  frontend/src/components/Card/MoimCard.style.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/components/Card/MoimCard.type.ts
  frontend/src/components/Input/MoimInput.style.ts
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/components/Input/MoimInput.type.ts
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/components/MoimCardList/MoimCardList.type.ts
  frontend/src/constants/endpoints.ts
  frontend/src/constants/poclies.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useAddMoim.ts
  frontend/src/hooks/queries/useMoims.ts
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomButtonWrapper.tsx
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomWrapper.style.ts
  frontend/src/layouts/FormLayout/FormHeader/FormHeader.tsx
  frontend/src/layouts/FormLayout/FormLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/layouts/HomeLayout.tsx/mockData.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MoimCreationPage/MoimCreatePage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreatePage.util.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.constant.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimList.tsx
  frontend/src/pages/MoimRegister.tsx
  frontend/src/pages/TmpAddMoim.tsx
  frontend/src/pages/TmpMain.tsx
  frontend/src/queryClient.ts
  frontend/src/reset.ts
  frontend/src/router.tsx
  frontend/src/type/index.ts
  frontend/src/types/index.d.ts
  frontend/src/utils/formatters.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: FE, ⚒️ 리팩터링

#65 develop-frontend를 develop에 머지
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/endPoints.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/button.styles.ts
  frontend/src/common/assets/back.svg
  frontend/src/common/reset.style.ts
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/Button.type.ts
  frontend/src/components/Card/MoimCard.style.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/components/Card/MoimCard.type.ts
  frontend/src/components/Input/MoimInput.style.ts
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/components/Input/MoimInput.type.ts
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/components/MoimCardList/MoimCardList.type.ts
  frontend/src/constants/endpoints.ts
  frontend/src/constants/poclies.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useAddMoim.ts
  frontend/src/hooks/queries/useMoims.ts
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomButtonWrapper.tsx
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomWrapper.style.ts
  frontend/src/layouts/FormLayout/FormHeader/FormHeader.tsx
  frontend/src/layouts/FormLayout/FormLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/layouts/HomeLayout.tsx/mockData.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MoimCreationPage/MoimCreatePage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreatePage.util.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.constant.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimList.tsx
  frontend/src/pages/MoimRegister.tsx
  frontend/src/pages/TmpAddMoim.tsx
  frontend/src/pages/TmpMain.tsx
  frontend/src/queries/useMoims.ts
  frontend/src/queryClient.ts
  frontend/src/reset.ts
  frontend/src/router.tsx
  frontend/src/type/index.ts
  frontend/src/types/index.d.ts
  frontend/src/utils/formatters.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: FE, ⚒️ 리팩터링

#75 chore: Storybook에 emotion 설정
  frontend/.storybook/main.ts
  frontend/package-lock.json
  frontend/package.json
Labels: FE, ⚙ 환경설정

#74 Controller에서 Swagger 코드 분리
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/controller/MoimSwagger.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/endPoints.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/button.styles.ts
  frontend/src/common/assets/back.svg
  frontend/src/common/reset.style.ts
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Button/Button.type.ts
  frontend/src/components/Card/MoimCard.style.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/components/Card/MoimCard.type.ts
  frontend/src/components/Input/MoimInput.style.ts
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/components/Input/MoimInput.type.ts
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/components/MoimCardList/MoimCardList.type.ts
  frontend/src/constants/endpoints.ts
  frontend/src/constants/poclies.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useAddMoim.ts
  frontend/src/hooks/queries/useMoims.ts
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomButtonWrapper.tsx
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomWrapper.style.ts
  frontend/src/layouts/FormLayout/FormHeader/FormHeader.tsx
  frontend/src/layouts/FormLayout/FormLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/layouts/HomeLayout.tsx/mockData.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MoimCreationPage/MoimCreatePage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreatePage.util.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.constant.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimList.tsx
  frontend/src/pages/MoimRegister.tsx
  frontend/src/pages/TmpAddMoim.tsx
  frontend/src/pages/TmpMain.tsx
  frontend/src/queries/useMoims.ts
  frontend/src/queryClient.ts
  frontend/src/reset.ts
  frontend/src/router.tsx
  frontend/src/type/index.ts
  frontend/src/types/index.d.ts
  frontend/src/utils/formatters.ts
  frontend/tsconfig.json
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: BE, ⚒️ 리팩터링

#76 커스텀 예외 처리
  backend/src/main/java/mouda/backend/exception/ErrorResponse.java
  backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/mouda/backend/exception/MoudaException.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
  backend/src/main/java/mouda/backend/moim/exception/MoimException.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
Labels: BE, 🌱 기능추가

#79 모임상세, 모임 참여 API 연결 로직 구현
  frontend/src/apis/apiconfig.ts
  frontend/src/apis/gets.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/components/Card/MoimCard.tsx
  frontend/src/components/MoimCardList/MoimCardList.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useAddMoim.ts
  frontend/src/hooks/mutaions/useJoinMoim.ts
  frontend/src/hooks/queries/useMoim.ts
  frontend/src/pages/MoimCreationPage/MoimCreatePage.hook.ts
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/TempDetail/TempDetailPage.tsx
  frontend/src/queryClient.ts
  frontend/src/router.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#81 스프린트 2-2 레이아웃 구현
  frontend/src/layouts/CompleteLayout/CompleteBottomWrapper/CompleteBottomWrapper.style.ts
  frontend/src/layouts/CompleteLayout/CompleteBottomWrapper/CompleteBottomWrapper.tsx
  frontend/src/layouts/CompleteLayout/CompleteContentContainer/CompleteContentContainer.stories.tsx
  frontend/src/layouts/CompleteLayout/CompleteContentContainer/CompleteContentContainer.style.ts
  frontend/src/layouts/CompleteLayout/CompleteContentContainer/CompleteContentContainer.tsx
  frontend/src/layouts/CompleteLayout/CompleteLayout.style.ts
  frontend/src/layouts/CompleteLayout/CompleteLayout.tsx
  frontend/src/layouts/InformationLayout/InformationBottomWrapper/InformationBottomWrapper.style.ts
  frontend/src/layouts/InformationLayout/InformationBottomWrapper/InformationBottomWrapper.tsx
  frontend/src/layouts/InformationLayout/InformationContentContainer/InformationContentContainer.stories.tsx
  frontend/src/layouts/InformationLayout/InformationContentContainer/InformationContentContainer.style.ts
  frontend/src/layouts/InformationLayout/InformationContentContainer/InformationLayoutContentContainer.tsx
  frontend/src/layouts/InformationLayout/InformationLayout.stories.tsx
  frontend/src/layouts/InformationLayout/InformationLayout.style.ts
  frontend/src/layouts/InformationLayout/InformationLayout.tsx
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.stories.tsx
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.style.ts
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.tsx
Labels: FE, 🌱 기능추가

#80 모임 상세 페이지 컴포넌트 개발
  frontend/.storybook/preview.tsx
  frontend/src/components/MoimDescription/MoimDescription.stories.tsx
  frontend/src/components/MoimDescription/MoimDescription.style.ts
  frontend/src/components/MoimDescription/MoimDescription.tsx
  frontend/src/components/MoimInformation/MoimInformation.stories.tsx
  frontend/src/components/MoimInformation/MoimInformation.style.ts
  frontend/src/components/MoimInformation/MoimInformation.tsx
  frontend/src/components/MoimSummary/MoimSummary.stories.tsx
  frontend/src/components/MoimSummary/MoimSummary.style.ts
  frontend/src/components/MoimSummary/MoimSummary.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#91 feat: 2-2차 스프린트 레이아웃, 컴포넌트, API 통합
  frontend/src/apis/posts.ts
  frontend/src/components/MoimDescription/MoimDescription.tsx
  frontend/src/components/MoimInformation/MoimInformation.tsx
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useJoinMoim.ts
  frontend/src/layouts/CompleteLayout/CompleteContentContainer/CompleteContentContainer.style.ts
  frontend/src/layouts/CompleteLayout/CompleteLayout.style.ts
  frontend/src/layouts/CompleteLayout/CompleteLayout.tsx
  frontend/src/layouts/InformationLayout/InformationLayout.stories.tsx
  frontend/src/pages/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/ParticipationCompletePage/ParticipationCompletePage.tsx
  frontend/src/pages/TempDetail/TempDetailPage.tsx
  frontend/src/router.tsx
  frontend/webpack.common.js
Labels: FE, 🌱 기능추가

#84 env 설정, msw 설정
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apis/endPoints.ts
  frontend/src/apis/env.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handlers/moimHandler.ts
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: FE, ⚙ 환경설정

#86 stylelint 적용을 위한 vscod 환경 설정
  frontend/.vscode/settings.json
Labels: FE, ⚙ 환경설정

#78 날짜 / 시간 및 기타 코드 컨벤션 통일
  backend/src/main/java/mouda/backend/common/RestResponse.java
  backend/src/main/java/mouda/backend/config/CorsConfig.java
  backend/src/main/java/mouda/backend/config/JacksonConfig.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/controller/MoimSwagger.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimDetailsFindResponse.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimFindAllResponse.java
  backend/src/test/java/mouda/backend/config/JacksonConfigTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
  backend/src/test/resources/application.yml
Labels: BE, ⚒️ 리팩터링

#95 스프린트 2-3 기능 추가요구사항 구현
  frontend/src/apis/posts.ts
  frontend/src/hooks/mutaions/useJoinMoim.ts
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
Labels: FE, 🌱 기능추가

#93 env를 통한 MSW 분기 처리
  frontend/package.json
  frontend/src/index.tsx
  frontend/webpack.common.js
Labels: FE, ⚙ 환경설정

#100 서비스 테스트 시 레포지토리에서 잘못 호출되는 메서드를 수정
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 👀 테스트

#96 참여자 닉네임 생성, 모임의 참여자 조회 기능 생성
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/repository/MemberRepository.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimJoinRequest.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimDetailsFindResponse.java
  backend/src/main/java/mouda/backend/moim/dto/response/MoimFindAllResponse.java
  backend/src/main/java/mouda/backend/moim/service/MoimService.java
  backend/src/test/java/mouda/backend/config/DatabaseCleaner.java
  backend/src/test/java/mouda/backend/member/repository/MemberRepositoryTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 🌱 기능추가

#98 미적용된 스타일 적용
  frontend/package.json
  frontend/src/common/common.style.ts
  frontend/src/common/reset.style.ts
  frontend/src/components/Button/Button.style.ts
  frontend/src/components/Card/MoimCard.style.ts
  frontend/src/components/Input/MoimInput.style.ts
  frontend/src/components/MoimCardList/MoimCardList.style.ts
  frontend/src/components/MoimDescription/MoimDescription.style.ts
  frontend/src/components/MoimInformation/MoimInformation.style.ts
  frontend/src/components/MoimSummary/MoimSummary.style.ts
  frontend/src/layouts/CompleteLayout/CompleteBottomWrapper/CompleteBottomWrapper.style.ts
  frontend/src/layouts/CompleteLayout/CompleteContentContainer/CompleteContentContainer.style.ts
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomWrapper.style.ts
  frontend/src/layouts/FormLayout/FormHeader/FormHeader.style.ts
  frontend/src/layouts/FormLayout/FormMain/FormMain.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeFixedButtonWrapper/HomeFixedButtonWrapper.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeMain/HomeMain.style.ts
  frontend/src/layouts/InformationLayout/InformationBottomWrapper/InformationBottomWrapper.style.ts
  frontend/src/layouts/InformationLayout/InformationContentContainer/InformationContentContainer.style.ts
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.style.ts
Labels: FE, 👻 사소한 수정

#102 useMoimInfoInput훅 테스트, MoimInfoInput validate함수 테스트 작성
  frontend/.gitignore
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/poclies.ts
  frontend/src/pages/MoimCreationPage/MoimCreatePage.util.test.tsx
  frontend/src/pages/MoimCreationPage/useMoimInfoInput.test.tsx
  frontend/tsconfig.json
Labels: FE, 👀 테스트

#111 참여자 목록을 보여주는 기능 추가
  frontend/src/components/MoimDescription/MoimDescription.stories.tsx
  frontend/src/components/MoimDescription/MoimDescription.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/types/index.d.ts
Labels: FE, 🌱 기능추가

#115 프론트엔드 CI 스크립트 내용 추가
  .github/workflows/ci-frontend.yml
Labels: FE, 🌱 기능추가

#125 백엔드 CI / CD 스크립트 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cicd-backend-dev.yml
  .github/workflows/pr-test.yml
Labels: BE, ⚒️ 리팩터링

#118 desktop 환경에서의 max width 적용 및 상수화
  frontend/src/common/reset.style.ts
  frontend/src/constants/styles.ts
  frontend/src/layouts/FormLayout/FormBottomWrapper/FormBottomWrapper.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeFixedButtonWrapper/HomeFixedButtonWrapper.style.ts
  frontend/src/layouts/InformationLayout/InformationBottomWrapper/InformationBottomWrapper.style.ts
Labels: FE, 🌱 기능추가

#122 pretendard 폰트 추가 및 기본 폰트 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-Black.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-Bold.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-ExtraBold.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-ExtraLight.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-Light.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-Medium.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-Regular.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-SemiBold.subset.woff2
  frontend/src/common/assets/fonts/woff2-subset/Pretendard-Thin.subset.woff2
  frontend/src/common/assets/fonts/woff2/PretendardVariable.woff2
  frontend/src/common/font.style.ts
  frontend/src/common/reset.style.ts
  frontend/src/custom.d.ts
  frontend/webpack.common.js
Labels: FE, 🌱 기능추가

#134 하단 페이지 수정
  frontend/src/layouts/CompleteLayout/CompleteBottomWrapper/CompleteBottomWrapper.style.ts
Labels: FE, 🚑 버그

#136 피그마 디자인 시스템 세팅
  frontend/.storybook/preview.tsx
  frontend/src/ emotion.d.ts
  frontend/src/App.tsx
  frontend/src/common/font.style.ts
  frontend/src/common/theme/colorPalette.ts
  frontend/src/common/theme/semantic.ts
  frontend/src/common/theme/theme.style.ts
  frontend/src/common/theme/theme.type.ts
  frontend/src/common/theme/typography.ts
  frontend/src/constants/queryKeys.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.tsx
Labels: FE, 🌱 기능추가

#138 max-width theme으로 변경
  frontend/src/common/reset.style.ts
  frontend/src/common/theme/layout.ts
  frontend/src/common/theme/theme.style.ts
  frontend/src/common/theme/theme.type.ts
  frontend/src/emotion.d.ts
Labels: FE, 👻 사소한 수정

#142 현재 모임 상태 태그구현
  frontend/src/common/theme/theme.type.ts
  frontend/src/common/theme/typography.ts
  frontend/src/components/Tag/Tag.stories.tsx
  frontend/src/components/Tag/Tag.style.ts
  frontend/src/components/Tag/Tag.tsx
Labels: FE, 🌱 기능추가

#143 로그인 페이지 정적 UI 구현
  frontend/src/components/LoginForm/LoginForm.stories.tsx
  frontend/src/components/LoginForm/LoginForm.style.ts
  frontend/src/components/LoginForm/LoginForm.tsx
  frontend/src/constants/routes.ts
  frontend/src/layouts/LoginLayout/LoginFooter/LoginFooter.style.ts
  frontend/src/layouts/LoginLayout/LoginFooter/LoginFooter.tsx
  frontend/src/layouts/LoginLayout/LoginHeader/LoginHeader.style.ts
  frontend/src/layouts/LoginLayout/LoginHeader/LoginHeader.tsx
  frontend/src/layouts/LoginLayout/LoginLayout.style.ts
  frontend/src/layouts/LoginLayout/LoginLayout.tsx
  frontend/src/layouts/LoginLayout/LoginMain/LoginMain.style.ts
  frontend/src/layouts/LoginLayout/LoginMain/LoginMain.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/router.tsx
Labels: FE, 🌱 기능추가

#120 입력값과 엔티티 필드에 대한 유효성 검증 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/moim/controller/MoimController.java
  backend/src/main/java/mouda/backend/moim/domain/Moim.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimCreateRequest.java
  backend/src/main/java/mouda/backend/moim/dto/request/MoimJoinRequest.java
  backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
  backend/src/test/java/mouda/backend/config/JacksonConfigTest.java
  backend/src/test/java/mouda/backend/member/domain/MemberTest.java
  backend/src/test/java/mouda/backend/member/repository/MemberRepositoryTest.java
  backend/src/test/java/mouda/backend/moim/domain/MoimTest.java
  backend/src/test/java/mouda/backend/moim/service/MoimServiceTest.java
Labels: BE, 🌱 기능추가

#156 로그인 처리 공통화를 위한 ArgumentResolver 및 Interceptor 구현
  backend/src/main/java/mouda/backend/auth/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/service/AuthService.java
  backend/src/main/java/mouda/backend/config/WebMvcConfig.java
  backend/src/main/java/mouda/backend/config/argumentresolver/LoginMember.java
  backend/src/main/java/mouda/backend/config/argumentresolver/LoginMemberArgumentResolver.java
  backend/src/main/java/mouda/backend/config/interceptor/AuthenticationCheckInterceptor.java
  backend/src/main/java/mouda/backend/security/JwtProvider.java
  backend/src/test/java/mouda/backend/auth/controller/AuthControllerTest.java
  backend/src/test/java/mouda/backend/config/JacksonConfigTest.java
  backend/src/test/java/mouda/backend/fixture/TokenFixture.java
Labels: BE, 🌱 기능추가

#152 사용자 프로필 바 컴포넌트 구현
  frontend/.storybook/main.ts
  frontend/src/common/assets/crown.svg
  frontend/src/common/assets/empty_profile.svg
  frontend/src/components/Profile/ProfileCard.stories.tsx
  frontend/src/components/Profile/ProfileCard.style.ts
  frontend/src/components/Profile/ProfileCard.tsx
  frontend/src/components/Profile/ProfileFrame.stories.tsx
  frontend/src/components/Profile/ProfileFrame.style.ts
  frontend/src/components/Profile/ProfileFrame.tsx
  frontend/src/components/ProfileList/ProfileList.stories.tsx
  frontend/src/components/ProfileList/ProfileList.style.ts
  frontend/src/components/ProfileList/ProfileList.tsx
  frontend/src/custom.d.ts
  frontend/src/types/index.d.ts
  frontend/webpack.common.js
Labels: FE, 🌱 기능추가

#163 401 인증 오류에서 500코드가 나가는 버그 수정
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/config/interceptor/AuthenticationCheckInterceptor.java
  backend/src/main/java/mouda/backend/exception/GlobalExceptionHandler.java
Labels: BE, 🚑 버그
