Repository woowacourse-teams/2024-mouda, pull requests merged in 2024-10, with the labels that each got.

#589 내기 기능 구현
  backend/build.gradle
  backend/src/main/java/mouda/backend/bet/business/BetScheduler.java
  backend/src/main/java/mouda/backend/bet/business/BetService.java
  backend/src/main/java/mouda/backend/bet/domain/Bet.java
  backend/src/main/java/mouda/backend/bet/domain/BetDetails.java
  backend/src/main/java/mouda/backend/bet/domain/BetRole.java
  backend/src/main/java/mouda/backend/bet/domain/BettingTime.java
  backend/src/main/java/mouda/backend/bet/domain/Loser.java
  backend/src/main/java/mouda/backend/bet/domain/Participant.java
  backend/src/main/java/mouda/backend/bet/entity/BetDarakbangMemberEntity.java
  backend/src/main/java/mouda/backend/bet/entity/BetEntity.java
  backend/src/main/java/mouda/backend/bet/implement/BetFinder.java
  backend/src/main/java/mouda/backend/bet/implement/BetSorter.java
  backend/src/main/java/mouda/backend/bet/implement/BetWriter.java
  backend/src/main/java/mouda/backend/bet/implement/ParticipantFinder.java
  backend/src/main/java/mouda/backend/bet/infrastructure/BetDarakbangMemberRepository.java
  backend/src/main/java/mouda/backend/bet/infrastructure/BetRepository.java
  backend/src/main/java/mouda/backend/bet/presentation/controller/BetController.java
  backend/src/main/java/mouda/backend/bet/presentation/controller/swagger/BetSwagger.java
  backend/src/main/java/mouda/backend/bet/presentation/request/BetCreateRequest.java
  backend/src/main/java/mouda/backend/bet/presentation/response/BetCreateResponse.java
  backend/src/main/java/mouda/backend/bet/presentation/response/BetFindAllResponse.java
  backend/src/main/java/mouda/backend/bet/presentation/response/BetFindAllResponses.java
  backend/src/main/java/mouda/backend/bet/presentation/response/BetFindResponse.java
  backend/src/main/java/mouda/backend/bet/presentation/response/BetResultResponse.java
  backend/src/main/java/mouda/backend/bet/presentation/response/ParticipantResponse.java
  backend/src/main/resources/application.yml
  backend/src/test/java/mouda/backend/bet/business/BetSchedulerTest.java
  backend/src/test/java/mouda/backend/bet/business/BetServiceTest.java
  backend/src/test/java/mouda/backend/bet/domain/BetTest.java
  backend/src/test/java/mouda/backend/bet/domain/BettingTimeTest.java
  backend/src/test/java/mouda/backend/bet/implement/BetFinderTest.java
  backend/src/test/java/mouda/backend/bet/implement/BetSorterTest.java
  backend/src/test/java/mouda/backend/bet/implement/ParticipantFinderTest.java
  backend/src/test/java/mouda/backend/bet/infrastructure/BetRepositoryTest.java
  backend/src/test/java/mouda/backend/common/fixture/BetEntityFixture.java
  backend/src/test/java/mouda/backend/common/fixture/BetFixture.java
  backend/src/test/resources/application.yml
Labels: BE, 🌱 기능추가

#588 애플 로그인 후 사용자 소셜 아이디를 받아오는 기능 구현
  .gitignore
  backend/src/main/java/mouda/backend/auth/Infrastructure/AppleOauthClient.java
  backend/src/main/java/mouda/backend/auth/Infrastructure/response/TokenResponse.java
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/auth/implement/AppleOauthManager.java
  backend/src/main/java/mouda/backend/auth/implement/KakaoOauthManager.java
  backend/src/main/java/mouda/backend/auth/implement/LoginManager.java
  backend/src/main/java/mouda/backend/auth/implement/OauthManager.java
  backend/src/main/java/mouda/backend/auth/implement/jwt/AccessTokenProvider.java
  backend/src/main/java/mouda/backend/auth/implement/jwt/ClientSecretProvider.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/swagger/AuthSwagger.java
  backend/src/main/java/mouda/backend/auth/util/TokenDecoder.java
  backend/src/main/java/mouda/backend/member/domain/LoginDetail.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/test/java/mouda/backend/auth/Infrastructure/AppleOauthClientTest.java
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/implement/LoginManagerTest.java
  backend/src/test/java/mouda/backend/auth/implement/OauthManagerTest.java
  backend/src/test/java/mouda/backend/common/fixture/MemberFixture.java
  backend/src/test/resources/application.yml
Labels: BE, 🌱 기능추가

#599 개발 서버에 애플 로그인 Private Key를 추가
  .github/workflows/cicd-backend-dev.yml
Labels: BE, ⚙ 환경설정

#586 다락방 멤버 조회 권한 삭제
  backend/src/main/java/mouda/backend/darakbangmember/business/DarakbangMemberService.java
  backend/src/test/java/mouda/backend/darakbangmember/business/DarakbangMemberServiceTest.java
Labels: BE, 🚑 버그

#606 구글 로그인, apple로그인 구현, 기존 카카오톡 로그인 사용자를 위한 데이터 이전 로직 구현
  frontend/src/apis/apiClient.ts
  frontend/src/apis/auth.ts
  frontend/src/common/assets/googleLogin.svg
  frontend/src/common/lastDarakbangManager.tsx
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.style.ts
  frontend/src/components/GoogleLoginButton/GoogleLoginButton.tsx
  frontend/src/components/Icons/AppleOAuthIcon.tsx
  frontend/src/components/Icons/KakaoOAuthIcon.tsx
  frontend/src/constants/routes.ts
  frontend/src/global.d.ts
  frontend/src/index.html
  frontend/src/layouts/InformationLayout/InformationBottomWrapper/InformationBottomWrapper.style.ts
  frontend/src/layouts/LoginLayout/LoginFooter/LoginFooter.style.ts
  frontend/src/layouts/LoginLayout/LoginLayout.style.ts
  frontend/src/layouts/LoginLayout/LoginLayout.tsx
  frontend/src/pages/Login/DataMigrationPage/Explanation/DataMigrationExplanationPage.style.ts
  frontend/src/pages/Login/DataMigrationPage/Explanation/DataMigrationExplanationPage.tsx
  frontend/src/pages/Login/DataMigrationPage/Select/OAuthSelectPage.stories.tsx
  frontend/src/pages/Login/DataMigrationPage/Select/OAuthSelectPage.tsx
  frontend/src/pages/Login/HomePage/HomePage.tsx
  frontend/src/pages/Login/KakaoOAuthLoginPage/KakaoOAuthLoginPage.tsx
  frontend/src/pages/Login/OAuthLoginPage/OAuthLoginPage.tsx
  frontend/src/pages/Moim/MainPage/MainPage.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileList.style.ts
  frontend/src/pages/Mypage/MyPage.stories.tsx
  frontend/src/pages/Mypage/MyPage.style.ts
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.tsx
  frontend/src/pages/Navigator/SlashRoute.tsx
  frontend/src/queryClient.ts
  frontend/src/routes/router.tsx
  frontend/src/utils/checkAuthentication.ts
  frontend/src/utils/tokenManager.ts
  frontend/tsconfig.json
Labels: FE, 🌱 기능추가

#610 마이페이지 수정 및 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/GoogleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/auth/implement/LoginManager.java
  backend/src/main/java/mouda/backend/auth/presentation/request/AppleOauthRequest.java
  backend/src/main/java/mouda/backend/common/config/S3Config.java
  backend/src/main/java/mouda/backend/darakbangmember/business/DarakbangMemberService.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/main/java/mouda/backend/darakbangmember/exception/DarakbangMemberErrorMessage.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/DarakbangMemberWriter.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/ImageParser.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/S3Client.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/controller/DarakbangMemberController.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/controller/swagger/DarakbangMemberSwagger.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/request/DarakbangMemberInfoRequest.java
  backend/src/main/java/mouda/backend/member/business/MemberService.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/presentation/controller/MemberController.java
  backend/src/main/java/mouda/backend/member/presentation/controller/swagger/MemberSwagger.java
  backend/src/main/java/mouda/backend/member/presentation/response/DarakbangMemberInfoResponse.java
  backend/src/main/java/mouda/backend/member/presentation/response/MemberFindResponse.java
  backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/implement/LoginManagerTest.java
  backend/src/test/java/mouda/backend/common/fixture/DarakbangMemberFixture.java
  backend/src/test/java/mouda/backend/common/fixture/DarakbangSetUp.java
  backend/src/test/java/mouda/backend/common/fixture/MemberFixture.java
  backend/src/test/java/mouda/backend/darakbangmember/business/DarakbangMemberServiceTest.java
  backend/src/test/java/mouda/backend/darakbangmember/implement/DarakbangMemberWriterTest.java
  backend/src/test/java/mouda/backend/darakbangmember/implement/ImageParserTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🌱 기능추가

#616 마이페이지 고도화, 프로필 정보 변경 기능 추가
  frontend/src/apis/apiClient.ts
  frontend/src/apis/deletes.ts
  frontend/src/apis/endPoints.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/common/assets/edit.svg
  frontend/src/common/assets/setting.svg
  frontend/src/common/getRoutes.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useDeleteMyInfo.ts
  frontend/src/hooks/mutaions/useEditMyInfo.ts
  frontend/src/layouts/InformationLayout/InformationContentContainer/InformationLayoutContentContainer.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler/myInfoHandler.ts
  frontend/src/pages/Mypage/MyPage.style.ts
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Mypage/SettingPage/SettingPage.tsx
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.style.ts
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.tsx
  frontend/src/pages/Mypage/components/MineInfoCard/MoinInfoCard.stories.tsx
  frontend/src/pages/Mypage/components/MyInfoTabBar/MyInfoTabBar.style.ts
  frontend/src/pages/Mypage/components/MyInfoTabBar/MyInfoTabBar.tsx
  frontend/src/pages/Mypage/components/SettingCard/SettingCard.style.ts
  frontend/src/pages/Mypage/components/SettingCard/SettingCard.tsx
  frontend/src/pages/Mypage/components/SettingList/SettingList.style.ts
  frontend/src/pages/Mypage/components/SettingList/SettingList.tsx
  frontend/src/routes/router.tsx
Labels: FE, ⚙ 환경설정

#582 소셜 로그인한 회원 탈퇴 기능 구현
  backend/src/main/java/mouda/backend/member/implement/MemberWriter.java
  backend/src/test/java/mouda/backend/auth/implement/MemberWriterTest.java
Labels: BE, 🌱 기능추가

#635 애플 서버로부터 사용자 정보를 받는 기능 구현
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/implement/LoginManager.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleAuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/request/AppleOauthRequest.java
  backend/src/main/java/mouda/backend/member/domain/LoginDetail.java
  backend/src/main/java/mouda/backend/member/implement/MemberFinder.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
Labels: BE, 🌱 기능추가

#593 ChatPage, MainPage, PleasePage페이지를 ListLayoutPage로 공통화
  frontend/src/common/assets/refresh.svg
  frontend/src/common/reset.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.stories.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewLayout.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewLayout.tsx
  frontend/src/layouts/DefaultPageLayout/DefaultPageLayout.tsx
  frontend/src/layouts/DefaultPageLayout/DefaultPageMain/DefaultPageMain.style.ts
  frontend/src/layouts/DefaultPageLayout/DefaultPageMain/DefaultPageMain.tsx
  frontend/src/layouts/DefaultPageLayout/DefaultpageLayout.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.style.ts
  frontend/src/layouts/HomeLayout.tsx/HomeLayout.tsx
  frontend/src/layouts/ListLayout/ListLayout.style.ts
  frontend/src/layouts/ListLayout/ListLayout.tsx
  frontend/src/layouts/ListLayout/ListMain/ListMain.style.ts
  frontend/src/layouts/ListLayout/ListMain/ListMain.tsx
  frontend/src/layouts/PleaseLayout/PleaseHeader/PleaseHeader.style.ts
  frontend/src/layouts/PleaseLayout/PleaseHeader/PleaseHeader.tsx
  frontend/src/layouts/PleaseLayout/PleaseLayout.tsx
  frontend/src/layouts/PleaseLayout/PleaseMain/PleaseMain.style.ts
  frontend/src/layouts/PleaseLayout/PleaseMain/PleaseMain.tsx
  frontend/src/layouts/SelectLayout/SelectLayout.tsx
  frontend/src/layouts/components/DoubleTriHeader/DoubleTriHeader.style.ts
  frontend/src/layouts/components/DoubleTriHeader/DoubleTriHeader.tsx
  frontend/src/layouts/components/FixedBottomButtonWrapper/FixedBottomButtonWrapper.style.ts
  frontend/src/layouts/components/FixedBottomButtonWrapper/FixedBottomButtonWrapper.tsx
  frontend/src/layouts/components/FixedCreationButtonWrapper/FixedCreateButtonWrapper.tsx
  frontend/src/layouts/components/FixedCreationButtonWrapper/FixedCreationButtonWrapper.style.ts
  frontend/src/layouts/components/ListContent/ListContent.style.ts
  frontend/src/layouts/components/ListContent/ListContent.tsx
  frontend/src/layouts/components/NavigationBarWrapper/NavigationBarWrapper.style.ts
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.style.ts
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.tsx
  frontend/src/pages/Bet/BetListPage/BetListPage.tsx
  frontend/src/pages/Chatting/ChatPage/ChatListSkeleton/ChatCardListSkeleton.style.ts
  frontend/src/pages/Chatting/ChatPage/ChatListSkeleton/ChatCardListSkeleton.tsx
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Moim/MainPage/MainPage.tsx
  frontend/src/pages/Moim/MainPage/components/HomeMainContent/MoimCardList/MoimCardList.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Please/PleasePage/PleasePage.tsx
Labels: FE, ⚒️ 리팩터링

#634 Bet 예외 추가 및 예외 처리 통일
  backend/src/main/java/mouda/backend/bet/exception/BetErrorMessage.java
  backend/src/main/java/mouda/backend/bet/exception/BetException.java
  backend/src/main/java/mouda/backend/bet/implement/BetDarakbangMemberWriter.java
  backend/src/main/java/mouda/backend/bet/implement/BetFinder.java
  backend/src/main/java/mouda/backend/bet/implement/BetWriter.java
  backend/src/main/java/mouda/backend/chat/entity/ChatRoomEntity.java
  backend/src/main/java/mouda/backend/chat/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/chat/implement/BetAttributeManager.java
  backend/src/main/java/mouda/backend/chat/implement/ParticipantResolverRegistry.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/exception/MemberErrorMessage.java
  backend/src/main/java/mouda/backend/member/exception/MemberException.java
  backend/src/main/java/mouda/backend/moim/exception/ChamyoErrorMessage.java
  backend/src/main/java/mouda/backend/moim/exception/MoimErrorMessage.java
  backend/src/main/java/mouda/backend/moim/implement/writer/ChamyoWriter.java
  backend/src/main/java/mouda/backend/moim/implement/writer/MoimWriter.java
  backend/src/test/java/mouda/backend/bet/implement/BetFinderTest.java
  backend/src/test/java/mouda/backend/chat/implement/BetAttributeManagerTest.java
  backend/src/test/java/mouda/backend/chat/implement/ParticipantResolverRegistryTest.java
Labels: BE, 🌱 기능추가

#640 Chat 엔티티와 도메인 분리
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
  backend/src/main/java/mouda/backend/chat/domain/ChatWithAuthor.java
  backend/src/main/java/mouda/backend/chat/domain/Chats.java
  backend/src/main/java/mouda/backend/chat/entity/ChatEntity.java
  backend/src/main/java/mouda/backend/chat/entity/ChatType.java
  backend/src/main/java/mouda/backend/chat/implement/ChatRoomFinder.java
  backend/src/main/java/mouda/backend/chat/implement/ChatWriter.java
  backend/src/main/java/mouda/backend/chat/presentation/request/DateTimeConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/presentation/request/PlaceConfirmRequest.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ChatFindDetailResponse.java
  backend/src/test/java/mouda/backend/chat/business/ChatRoomServiceTest.java
  backend/src/test/java/mouda/backend/common/fixture/ChatEntityFixture.java
Labels: BE, ⚒️ 리팩터링

#651 채팅 알림 메시지 형식 수정
  backend/src/main/java/mouda/backend/bet/domain/Bet.java
  backend/src/main/java/mouda/backend/chat/business/ChatService.java
  backend/src/main/java/mouda/backend/chat/implement/sender/ChatNotificationSender.java
  backend/src/main/java/mouda/backend/chat/util/DateTimeFormatter.java
  backend/src/main/java/mouda/backend/moim/business/ChatService.java
  backend/src/main/java/mouda/backend/moim/implement/finder/ChatRecipientFinder.java
  backend/src/main/java/mouda/backend/moim/implement/sender/ChamyoNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/sender/CommentNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/sender/MoimNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/sender/OldChatNotificationSender.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationEvent.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationType.java
  backend/src/main/java/mouda/backend/notification/exception/NotificationErrorMessage.java
  backend/src/main/java/mouda/backend/notification/exception/NotificationException.java
  backend/src/test/java/mouda/backend/moim/implement/finder/ChatRecipientFinderTest.java
  backend/src/test/java/mouda/backend/notification/implement/filter/ChatRoomSubscriptionFilterTest.java
Labels: BE, ⚒️ 리팩터링

#647 채팅방 안내면 진다 도입 후 바 ui 구현
  .github/workflows/ci-frontend.yml
  frontend/public/firebase-messaging-sw.js
  frontend/src/apis/gets.ts
  frontend/src/apis/patches.ts
  frontend/src/apis/posts.ts
  frontend/src/apis/responseTypes.ts
  frontend/src/components/GoogleLoginButton/GoogleLoginButton.tsx
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useConfirmDatetime.ts
  frontend/src/hooks/mutaions/useConfirmPlace.ts
  frontend/src/hooks/mutaions/useOpenChat.ts
  frontend/src/hooks/mutaions/useSendMessage.ts
  frontend/src/hooks/queries/useChatPreiview.ts
  frontend/src/hooks/queries/useChatRoomDetail.ts
  frontend/src/hooks/queries/useChats.test.tsx
  frontend/src/hooks/queries/useChats.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.stories.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.tsx
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewLayout.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewLayout.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.stories.tsx
  frontend/src/mocks/handler/chatHandler.ts
  frontend/src/mocks/handler/mockedChats.ts
  frontend/src/pages/Bet/BetDetailPage/BetDetailPage.tsx
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChatFilterTag/ChatFilterTag.stories.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChatFilterTag/ChatFilterTag.styles.ts
  frontend/src/pages/Chatting/ChatPage/components/ChatFilterTag/ChatFilterTag.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChatFilterTagList/ChatFilterTagList.styles.ts
  frontend/src/pages/Chatting/ChatPage/components/ChatFilterTagList/ChatFilterTagList.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChattingPreview/ChattingPreview.stories.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChattingPreview/ChattingPreview.style.ts
  frontend/src/pages/Chatting/ChatPage/components/ChattingPreview/ChattingPreview.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/Chat/Chat.stories.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/Chat/Chat.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChatInfoAccordion/ChatInfoAccordion.stories.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChatInfoAccordion/ChatInfoAccordion.styles.ts
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChatInfoAccordion/ChatInfoAccordion.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChatList/ChatList.stories.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChatList/ChatList.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/MoimInfoAccordion/MoimInfoAccordion.stories.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/MoimInfoAccordion/MoimInfoAccordion.tsx
  frontend/src/pages/Login/DataMigrationPage/Select/OAuthSelectPage.tsx
  frontend/src/pages/Moim/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/Moim/MoimModifyPage/MoimModifyPage.util.ts
  frontend/src/service/forgroundMessage.ts
  frontend/src/service/notification.ts
  frontend/src/types/index.d.ts
  frontend/src/types/typeGuards.ts
Labels: FE, 🌱 기능추가

#652 레이아웃 컴포넌트 병합 이슈 해결
  frontend/src/layouts/SelectLayout/SelectLayout.tsx
  frontend/src/layouts/components/TriSectionHeader/TriSectionHeader.style.ts
Labels: FE, 🚑 버그

#646 애플 로그인과 마이페이지 QA항목 개선
  .gitignore
  frontend/src/components/ProfileFrame/ProfileFrame.style.ts
  frontend/src/components/ProfileFrame/ProfileFrame.tsx
  frontend/src/pages/Login/DataMigrationPage/Select/OAuthSelectPage.tsx
  frontend/src/pages/Login/HomePage/HomePage.tsx
  frontend/src/pages/Login/OAuthLoginPage/OAuthLoginPage.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.style.ts
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.tsx
  frontend/src/pages/Mypage/components/SettingList/SettingList.tsx
Labels: FE, 🌱 기능추가

#663 애플 로그인 시 버그 수정과 코드 리팩토링 및 테스트
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleAuthController.java
  backend/src/main/java/mouda/backend/darakbangmember/business/DarakbangMemberService.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/ImageParser.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/controller/swagger/DarakbangMemberSwagger.java
  backend/src/test/java/mouda/backend/darakbangmember/business/DarakbangMemberServiceTest.java
Labels: BE, 🚑 버그

#667 안내면진다 버튼 문제 해결
  frontend/src/hooks/queries/useBet.ts
  frontend/src/pages/Bet/BetDetailPage/BetDetailPage.tsx
Labels: FE, 🚑 버그

#658 헤더 UI 문제 해결
  frontend/src/pages/Bet/BetListPage/BetListPage.tsx
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Mypage/MyPage.tsx
Labels: FE, 🚑 버그

#670 QA에서 나온 채팅방 버그 수정
  frontend/src/components/MissingFallback/MissingFallback.style.ts
  frontend/src/components/MissingFallback/MissingFallback.tsx
  frontend/src/layouts/ChattingRoomLayout/ChattingRoomLayout.style.ts
  frontend/src/mocks/handler/chatHandler.ts
  frontend/src/pages/Chatting/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/Moim/MainPage/MainPage.tsx
Labels: FE, 🌱 기능추가

#672 QA에서 나왔던 닉네임 validate 추가
  frontend/src/apis/deletes.ts
  frontend/src/common/assets/default_profile.svg
  frontend/src/common/assets/empty_profile.svg
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/components/ProfileFrame/ProfileFrame.style.ts
  frontend/src/components/ProfileFrame/ProfileFrame.tsx
  frontend/src/components/UserPreview/UserPreview.style.ts
  frontend/src/constants/poclies.ts
  frontend/src/pages/Mypage/MyPage.style.ts
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.style.ts
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.tsx
  frontend/src/pages/Mypage/hook/useMyPage.ts
  frontend/src/pages/Mypage/validate.ts
  frontend/src/utils/checkCanUseFirebase.ts
Labels: FE, 🌱 기능추가

#662 닉네임, 제목이 길 때 UI 깨지는 문제
  frontend/src/components/ProfileFrame/ProfileFrame.style.ts
  frontend/src/hooks/useNicknameWidthEffect.ts
  frontend/src/pages/Bet/BetDetailPage/BetDetailPage.style.ts
  frontend/src/pages/Bet/BetDetailPage/components/ProfileList/ProfileCard/ProfileCard.style.ts
  frontend/src/pages/Bet/BetDetailPage/components/ProfileList/ProfileCard/ProfileCard.tsx
  frontend/src/pages/Bet/BetListPage/components/BetCardList/BetCard/BetCard.style.ts
  frontend/src/pages/Bet/BetListPage/components/BetCardList/BetCard/BetCard.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/CommentList/CommentCard/CommentCard.style.ts
  frontend/src/pages/Moim/MoimDetailPage/components/CommentList/CommentCard/CommentCard.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileCard/ProfileCard.style.ts
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileCard/ProfileCard.tsx
Labels: FE, 🚑 버그

#665 chat 작성자 이름 오류 및 chatroom 조회 오류 수정
  backend/src/main/java/mouda/backend/bet/domain/Bet.java
  backend/src/main/java/mouda/backend/bet/domain/BetDetails.java
  backend/src/main/java/mouda/backend/bet/domain/BettingTime.java
  backend/src/main/java/mouda/backend/bet/entity/BetDarakbangMemberEntity.java
  backend/src/main/java/mouda/backend/bet/entity/BetEntity.java
  backend/src/main/java/mouda/backend/bet/exception/BetErrorMessage.java
  backend/src/main/java/mouda/backend/bet/implement/BetWriter.java
  backend/src/main/java/mouda/backend/chat/business/ChatService.java
  backend/src/main/java/mouda/backend/chat/domain/Author.java
  backend/src/main/java/mouda/backend/chat/domain/Chat.java
  backend/src/main/java/mouda/backend/chat/domain/ChatOwnership.java
  backend/src/main/java/mouda/backend/chat/domain/ChatRoom.java
  backend/src/main/java/mouda/backend/chat/domain/ChatWithAuthor.java
  backend/src/main/java/mouda/backend/chat/domain/Chats.java
  backend/src/main/java/mouda/backend/chat/domain/Participant.java
  backend/src/main/java/mouda/backend/chat/domain/Target.java
  backend/src/main/java/mouda/backend/chat/entity/ChatEntity.java
  backend/src/main/java/mouda/backend/chat/implement/BetChatPreviewManager.java
  backend/src/main/java/mouda/backend/chat/implement/ChatRoomFinder.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ChatFindUnloadedResponse.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ParticipantResponse.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/test/java/mouda/backend/bet/business/BetServiceTest.java
  backend/src/test/java/mouda/backend/bet/implement/BetFinderTest.java
  backend/src/test/java/mouda/backend/bet/implement/BetWriterTest.java
  backend/src/test/java/mouda/backend/bet/infrastructure/BetRepositoryTest.java
  backend/src/test/java/mouda/backend/chat/business/ChatRoomServiceTest.java
  backend/src/test/java/mouda/backend/chat/business/ChatServiceTest.java
  backend/src/test/java/mouda/backend/chat/implement/BetAttributeManagerTest.java
  backend/src/test/java/mouda/backend/chat/implement/BetChatPreviewManagerTest.java
  backend/src/test/java/mouda/backend/chat/implement/BetParticipantResolverTest.java
  backend/src/test/java/mouda/backend/chat/implement/ChatRoomDetailsFinderTest.java
  backend/src/test/java/mouda/backend/chat/implement/MoimParticipantResolverTest.java
  backend/src/test/java/mouda/backend/common/fixture/BetEntityFixture.java
  backend/src/test/java/mouda/backend/common/fixture/DarakbangMemberFixture.java
Labels: BE, 🚑 버그

#674 사용되지 않는 선언 삭제
  frontend/src/pages/Mypage/MyPage.tsx
Labels: FE, 🚑 버그

#677 회원 탈퇴 시 애플 서버에게 회원 권한 삭제를 요청하는 기능 구현
  backend/src/main/java/mouda/backend/auth/Infrastructure/AppleOauthClient.java
  backend/src/main/java/mouda/backend/auth/Infrastructure/response/AppleRefreshTokenResponse.java
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/presentation/business/CommonAuthService.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleAuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/swagger/AuthSwagger.java
  backend/src/main/java/mouda/backend/auth/presentation/request/AppleOauthRequest.java
  backend/src/main/java/mouda/backend/member/domain/LoginDetail.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/implement/MemberFinder.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
Labels: BE, 🌱 기능추가

#681 푸시 알림 클릭시 이동 문제 확인
  frontend/public/firebase-messaging-sw.js
  frontend/src/service/forgroundMessage.ts
Labels: FE, ⚒️ 리팩터링

#689 회원 탈퇴 시 논리 삭제 및 재가입 로직 구현
  backend/src/main/java/mouda/backend/auth/Infrastructure/AppleOauthClient.java
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/auth/business/result/LoginProcessResult.java
  backend/src/main/java/mouda/backend/auth/implement/LoginManager.java
  backend/src/main/java/mouda/backend/auth/presentation/business/CommonAuthService.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleAuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/swagger/AuthSwagger.java
  backend/src/main/java/mouda/backend/auth/presentation/response/KakaoLoginResponse.java
  backend/src/main/java/mouda/backend/member/domain/LoginDetail.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/domain/MemberStatus.java
  backend/src/main/java/mouda/backend/member/implement/MemberWriter.java
  backend/src/test/java/mouda/backend/auth/business/GoogleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/implement/LoginManagerTest.java
  backend/src/test/java/mouda/backend/auth/implement/MemberWriterTest.java
Labels: BE, 🌱 기능추가

#678 안내면진다 목록 정렬 수정 및 모임 상세 응답에서 ChatRoomId 추가
  backend/src/main/java/mouda/backend/bet/implement/BetSorter.java
  backend/src/main/java/mouda/backend/moim/business/MoimService.java
  backend/src/main/java/mouda/backend/moim/presentation/response/moim/MoimDetailsFindResponse.java
  backend/src/test/java/mouda/backend/bet/implement/BetSorterTest.java
Labels: BE, 🚑 버그

#691 로그인 관련 코드 리팩토링 및 사용자 전환 플로우 수정에 따른 로직 추가
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/GoogleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/auth/business/TestAuthService.java
  backend/src/main/java/mouda/backend/auth/business/result/LoginProcessResult.java
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/auth/implement/AppleOauthManager.java
  backend/src/main/java/mouda/backend/auth/implement/AppleUserInfoProvider.java
  backend/src/main/java/mouda/backend/auth/implement/GoogleUserInfoProvider.java
  backend/src/main/java/mouda/backend/auth/implement/JoinManager.java
  backend/src/main/java/mouda/backend/auth/implement/KakaoUserInfoProvider.java
  backend/src/main/java/mouda/backend/auth/implement/LoginManager.java
  backend/src/main/java/mouda/backend/auth/implement/jwt/AccessTokenProvider.java
  backend/src/main/java/mouda/backend/auth/presentation/business/CommonAuthService.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleAuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleUserInfoRequest.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AppleUserNameRequest.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/TestAuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/swagger/AuthSwagger.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/swagger/TestAuthSwagger.java
  backend/src/main/java/mouda/backend/auth/presentation/request/AppleOauthRequest.java
  backend/src/main/java/mouda/backend/auth/presentation/request/GoogleLoginRequest.java
  backend/src/main/java/mouda/backend/auth/presentation/request/KakaoConvertRequest.java
  backend/src/main/java/mouda/backend/auth/presentation/request/LoginRequest.java
  backend/src/main/java/mouda/backend/auth/presentation/response/LoginResponse.java
  backend/src/main/java/mouda/backend/member/business/MemberService.java
  backend/src/main/java/mouda/backend/member/domain/LoginDetail.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/implement/MemberFinder.java
  backend/src/main/java/mouda/backend/member/implement/MemberWriter.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/main/java/mouda/backend/member/presentation/controller/MemberController.java
  backend/src/main/java/mouda/backend/member/presentation/controller/swagger/MemberSwagger.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/business/GoogleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/business/KakaoAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/implement/AppleUserInfoProviderTest.java
  backend/src/test/java/mouda/backend/auth/implement/LoginManagerTest.java
  backend/src/test/java/mouda/backend/auth/implement/MemberFinderTest.java
  backend/src/test/java/mouda/backend/common/fixture/MemberFixture.java
  backend/src/test/resources/application.yml
Labels: BE, ⚒️ 리팩터링

#702 모니터링 대시보드를 구축하기 위한 설정 추가
  backend/build.gradle
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
Labels: BE, ⚙ 환경설정

#696 알림 재전송시 발생하는 오류 해결 및 로깅 개선
  backend/src/main/java/mouda/backend/notification/domain/FcmFailedResponse.java
  backend/src/main/java/mouda/backend/notification/domain/FcmToken.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/FcmNotificationSender.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/FcmResponseHandler.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/token/FcmTokenFinder.java
  backend/src/main/java/mouda/backend/notification/infrastructure/repository/FcmTokenRepository.java
  backend/src/main/java/mouda/backend/notification/util/FcmRetryAfterExtractor.java
Labels: BE, 🚑 버그

#701 구버전 채팅 제거 및 BeanCreationException 해결
  backend/src/main/java/mouda/backend/chat/implement/sender/ChatNotificationSender.java
  backend/src/main/java/mouda/backend/chat/implement/sender/ChatRecipientFinder.java
  backend/src/main/java/mouda/backend/common/config/data/DataSourceConfiguration.java
  backend/src/main/java/mouda/backend/moim/business/ChatService.java
  backend/src/main/java/mouda/backend/moim/domain/Chat.java
  backend/src/main/java/mouda/backend/moim/domain/ChatRoom.java
  backend/src/main/java/mouda/backend/moim/domain/ChatRooms.java
  backend/src/main/java/mouda/backend/moim/domain/ChatType.java
  backend/src/main/java/mouda/backend/moim/domain/ChatWithAuthor.java
  backend/src/main/java/mouda/backend/moim/domain/Chats.java
  backend/src/main/java/mouda/backend/moim/domain/EmptyChat.java
  backend/src/main/java/mouda/backend/moim/domain/MoimChat.java
  backend/src/main/java/mouda/backend/moim/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/moim/exception/ChatException.java
  backend/src/main/java/mouda/backend/moim/implement/finder/ChatFinder.java
  backend/src/main/java/mouda/backend/moim/implement/finder/ChatRoomFinder.java
  backend/src/main/java/mouda/backend/moim/implement/sender/OldChatNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/validator/ChatValidator.java
  backend/src/main/java/mouda/backend/moim/implement/writer/ChatWriter.java
  backend/src/main/java/mouda/backend/moim/infrastructure/ChatRepository.java
  backend/src/main/java/mouda/backend/moim/presentation/controller/ChatController.java
  backend/src/main/java/mouda/backend/moim/presentation/controller/swagger/ChatSwagger.java
  backend/src/main/java/mouda/backend/moim/presentation/request/chat/OldChatCreateRequest.java
  backend/src/main/java/mouda/backend/moim/presentation/request/chat/OldDateTimeConfirmRequest.java
  backend/src/main/java/mouda/backend/moim/presentation/request/chat/OldLastReadChatRequest.java
  backend/src/main/java/mouda/backend/moim/presentation/request/chat/OldPlaceConfirmRequest.java
  backend/src/main/java/mouda/backend/moim/presentation/response/chat/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/moim/presentation/response/chat/ChatPreviewResponse.java
  backend/src/main/java/mouda/backend/moim/presentation/response/chat/OldChatFindUnloadedResponse.java
  backend/src/main/java/mouda/backend/moim/presentation/response/chat/OldChatPreviewResponses.java
  backend/src/test/java/mouda/backend/chat/implement/ChatRecipientFinderTest.java
  backend/src/test/java/mouda/backend/common/fixture/ChatFixture.java
Labels: BE, 🚑 버그

#688 안내면진다 목록 기획, 디자인 변경사항 반영 및 버그 픽스
  frontend/src/components/Funnel/FunnelErrorMessage/FunnelErrorMessage.style.ts
  frontend/src/components/Funnel/FunnelErrorMessage/FunnelErrorMessage.tsx
  frontend/src/components/Icons/PeopleIcon.tsx
  frontend/src/components/Icons/RouletteIcon.tsx
  frontend/src/components/NavigationBar/NavigationBar.tsx
  frontend/src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
  frontend/src/constants/poclies.ts
  frontend/src/hooks/queries/useBets.ts
  frontend/src/hooks/queries/useBetsInterval.ts
  frontend/src/pages/Bet/BetCreationPage/BetCreationPage.tsx
  frontend/src/pages/Bet/BetCreationPage/components/Steps/TitleStep.tsx
  frontend/src/pages/Bet/BetCreationPage/components/Steps/WaitingMinutesStep.tsx
  frontend/src/pages/Bet/BetCreationPage/hooks/useBetCreationForm.ts
  frontend/src/pages/Bet/BetListPage/BetListPage.tsx
  frontend/src/pages/Bet/BetListPage/components/BetCardList/BetCard/BetCard.style.ts
  frontend/src/pages/Bet/BetListPage/components/BetCardList/BetCard/BetCard.tsx
  frontend/src/pages/Bet/BetListPage/components/BetCardList/BetCardList.tsx
  frontend/src/pages/Bet/BetListPage/components/BetList/BetList.tsx
  frontend/src/pages/Bet/components/Tag/Tag.tsx
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.hook.test.tsx
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.hook.ts
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.util.ts
  frontend/src/utils/calculateLeftMinutesUntilDeadline.ts
  frontend/src/utils/isApproachedByUrl.ts
Labels: FE, 🌱 기능추가, 🚑 버그

#693 웹 접근성 개선
  frontend/src/components/Button/BackArrowButton/BackArrowButton.tsx
  frontend/src/components/Funnel/FunnelInputErrorMessage/FunnelInputErrorMessage.tsx
  frontend/src/components/Funnel/FunnelQuestion/FunnelQuestion.tsx
  frontend/src/components/HighlightSpan/HighlightSpan.tsx
  frontend/src/index.html
  frontend/src/layouts/FunnelLayout/FunnelFooter/FunnelFooter.style.ts
  frontend/src/layouts/FunnelLayout/FunnelFooter/FunnelFooter.tsx
  frontend/src/pages/Darakbang/DarakbangCreationPage/DarakbangCreationModalContent/DarakbangCreationModalContent.tsx
  frontend/src/pages/Darakbang/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/Darakbang/DarakbangEntrancePage/DarakbangEntrancePage.tsx
  frontend/src/pages/Darakbang/DarakbangLandingPage/DarakbangLandingPage.tsx
  frontend/src/pages/Darakbang/DarakbangSelectOptionPage/DarakbangSelectOptionPage.tsx
  frontend/src/pages/Darakbang/DarakbangSelectPage/DarakbangSelectPage.tsx
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.hook.ts
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.util.ts
  frontend/src/pages/Moim/MoimCreationPage/components/Steps/DateAndTimeStep.tsx
  frontend/src/pages/Moim/MoimCreationPage/components/Steps/DescriptionStep.tsx
  frontend/src/pages/Moim/MoimCreationPage/components/Steps/MaxPeopleStep.tsx
  frontend/src/pages/Moim/MoimCreationPage/components/Steps/PlaceStep.tsx
  frontend/src/pages/Moim/MoimCreationPage/components/Steps/TitleStep.tsx
Labels: FE, ⚒️ 리팩터링

#698 룰렛 채팅 페이지 당첨자 배너 UI 개발
  frontend/src/common/assets/fonts/PartialSansKR/PartialSansKR-Regular.otf
  frontend/src/common/assets/fonts/PartialSansKR/PartialSansKR-Regular.woff2
  frontend/src/common/font.style.ts
  frontend/src/common/theme/theme.type.ts
  frontend/src/common/theme/typography.ts
  frontend/src/pages/Chatting/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/LooserBanner/LooserBanner.style.ts
  frontend/src/pages/Chatting/ChattingRoomPage/components/LooserBanner/LooserBanner.tsx
Labels: FE, 🌱 기능추가

#700 로그인페이지, 사용자 전환 페이지 UI 수정
  frontend/src/apis/auth.ts
  frontend/src/apis/deletes.ts
  frontend/src/common/assets/apple_cirecle.svg
  frontend/src/common/assets/happy_logo.svg
  frontend/src/common/assets/kakaoCircleOuathLogin.svg
  frontend/src/common/assets/main_logo.svg
  frontend/src/common/assets/missing_logo.svg
  frontend/src/common/getRoutes.ts
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.style.ts
  frontend/src/components/Fallback/HappyFallback/HappyFallback.stories.tsx
  frontend/src/components/Fallback/HappyFallback/HappyFallback.style.ts
  frontend/src/components/Fallback/HappyFallback/HappyFallback.tsx
  frontend/src/components/Fallback/MissingFallback/MissingFallback.stories.tsx
  frontend/src/components/Fallback/MissingFallback/MissingFallback.style.ts
  frontend/src/components/Fallback/MissingFallback/MissingFallback.tsx
  frontend/src/components/GoogleLoginButton/GoogleLoginButton.tsx
  frontend/src/components/Icons/AppleOAuthIcon.tsx
  frontend/src/components/Icons/KakaoOAuthIcon.tsx
  frontend/src/components/Icons/MainLogoIcon.tsx
  frontend/src/components/ProfileFrame/ProfileFrame.stories.tsx
  frontend/src/components/ProfileFrame/ProfileFrame.style.ts
  frontend/src/constants/poclies.ts
  frontend/src/constants/routes.ts
  frontend/src/hooks/mutaions/useMigrationOAuth.ts
  frontend/src/layouts/InformationLayout/InformationBottomWrapper/InformationBottomWrapper.style.ts
  frontend/src/layouts/LoginLayout/LoginFooter/LoginFooter.style.ts
  frontend/src/layouts/LoginLayout/LoginMain/LoginMain.style.ts
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChattingFooter/ChattingFooter.style.ts
  frontend/src/pages/Darakbang/DarakbangSelectPage/DarakbangSelectPage.tsx
  frontend/src/pages/Fallback/NotFoundPage/NotFoundPage.tsx
  frontend/src/pages/Login/DataMigrationPage/Explanation/DataMigrationExplanationPage.style.ts
  frontend/src/pages/Login/DataMigrationPage/Explanation/DataMigrationExplanationPage.tsx
  frontend/src/pages/Login/DataMigrationPage/Explanation/KakaoSelct.style.ts
  frontend/src/pages/Login/DataMigrationPage/Explanation/KakaoSelect.tsx
  frontend/src/pages/Login/DataMigrationPage/KakaoLogin/KakaoLoginPage.stories.tsx
  frontend/src/pages/Login/DataMigrationPage/KakaoLogin/KakaoLoginPage.style.ts
  frontend/src/pages/Login/DataMigrationPage/KakaoLogin/KakaoLoginPage.tsx
  frontend/src/pages/Login/DataMigrationPage/OAuthMigrationResult/OAuthMigrationResultPage.style.ts
  frontend/src/pages/Login/DataMigrationPage/OAuthMigrationResult/OAuthMigrationResultPage.tsx
  frontend/src/pages/Login/DataMigrationPage/Select/OAuthSelectPage.tsx
  frontend/src/pages/Login/HomePage/HomePage.style.ts
  frontend/src/pages/Login/HomePage/HomePage.tsx
  frontend/src/pages/Login/OAuthLoginPage/OAuthLoginPage.tsx
  frontend/src/pages/Moim/MainPage/components/HomeMainContent/MoimList/MoimList.tsx
  frontend/src/pages/Moim/MainPage/components/HomeMainContent/MyMoim/MyMoim.tsx
  frontend/src/pages/Moim/MainPage/components/HomeMainContent/MyZzimMoimList/MyZzimMoimList.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileCard/ProfileCard.stories.tsx
  frontend/src/pages/Mypage/hook/useMyPage.ts
  frontend/src/pages/Navigator/DarakbangInvitationRoute.tsx
  frontend/src/pages/Notification/components/NotificationList/NotificationList.tsx
  frontend/src/pages/Please/PleasePage/components/PleaseList/PleaseList.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🌱 기능추가

#712 머지 충돌 해결
  frontend/src/pages/Bet/BetListPage/components/BetList/BetList.tsx
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.hook.ts
Labels: FE, 🚑 버그

#705 모임 목록 페이지 접근성 개선
  frontend/src/components/NavigationBar/NavigationBar.tsx
  frontend/src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
  frontend/src/components/PlusButton/PlusButton.tsx
  frontend/src/components/RefreshButton/RefreshButton.tsx
  frontend/src/layouts/components/ListContent/ListContent.tsx
  frontend/src/pages/Moim/MainPage/MainPage.style.ts
  frontend/src/pages/Moim/MainPage/MainPage.tsx
  frontend/src/pages/Moim/MainPage/components/HomeMainContent/MoimCardList/MoimCard/MoimCard.tsx
  frontend/src/pages/Moim/MainPage/components/MoimTabBar/MoimTabBar.style.ts
  frontend/src/pages/Moim/MainPage/components/MoimTabBar/MoimTabBar.tsx
  frontend/src/pages/Moim/MoimDetailPage/MoimDetailPage.tsx
Labels: FE, 🌱 기능추가

#715 엔티티 스캔 패키지 지정
  backend/src/main/java/mouda/backend/common/config/data/DataSourceConfiguration.java
Labels: BE, 🚑 버그

#710 모임 상세목록 접근성 개선
  frontend/src/components/Button/Button.tsx
  frontend/src/components/Input/MessagInput/MessageInput.tsx
  frontend/src/components/KebabMenu/KebabMenu.tsx
  frontend/src/pages/Login/DataMigrationPage/Explanation/DataMigrationExplanationPage.style.ts
  frontend/src/pages/Moim/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/CommentList/CommentCard/CommentCard.style.ts
  frontend/src/pages/Moim/MoimDetailPage/components/CommentList/CommentCard/CommentCard.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/CommentList/CommentCard/CommentCardSkeleton.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/MoimDescription/MoimDescription.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/MoimInformation/MoimInformation.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/MoimSummary/MoimSummary.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileCard/ProfileCard.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileList.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/Tag/Tag.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/Zzim/ZzimButton.tsx
Labels: FE, 🌱 기능추가

#723 hotfix: 버그 수정
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.style.ts
  frontend/src/components/Icons/SolidArrow.tsx
  frontend/src/components/OptionsPanel/OptionsPanel.style.ts
  frontend/src/pages/Bet/BetDetailPage/BetDetailPage.tsx
  frontend/src/pages/Bet/BetResultPage/BetResultPage.tsx
  frontend/src/pages/Bet/components/Roulette/DrawRoulette.ts
  frontend/src/pages/Bet/components/Roulette/Roulette.styles.ts
  frontend/src/pages/Bet/components/Roulette/Roulette.tsx
  frontend/src/pages/Login/DataMigrationPage/OAuthMigrationResult/OAuthMigrationResultPage.tsx
Labels: FE, 🚨 긴급

#727 룰렛 수정
  frontend/src/components/UserPreview/UserPreview.style.ts
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.style.ts
  frontend/src/pages/Bet/BetDetailPage/BetDetailPage.tsx
  frontend/src/pages/Bet/BetResultPage/BetResultPage.tsx
  frontend/src/pages/Bet/components/Roulette/DrawRoulette.ts
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
Labels: FE, 🚑 버그

#729 로그인 페이지와 사용자 전환 플로우 변경
  frontend/src/components/Fallback/MissingFallback/MissingFallback.style.ts
  frontend/src/pages/Bet/BetListPage/components/BetList/BetList.tsx
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/ChattingRoomPage.tsx
  frontend/src/pages/Login/DataMigrationPage/OAuthMigrationResult/OAuthMigrationResultPage.tsx
  frontend/src/pages/Login/OAuthLoginPage/OAuthLoginPage.tsx
Labels: FE, 🚑 버그

#730 사용자 전환 시 구글, 애플 회원을 논리 삭제로 구현
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/GoogleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/auth/business/TestAuthService.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/response/LoginResponse.java
  backend/src/main/java/mouda/backend/member/business/MemberService.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/domain/MemberStatus.java
  backend/src/main/java/mouda/backend/member/implement/MemberFinder.java
  backend/src/main/java/mouda/backend/member/implement/MemberWriter.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/business/GoogleAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/business/KakaoAuthServiceTest.java
  backend/src/test/java/mouda/backend/auth/presentation/controller/AuthControllerTest.java
  backend/src/test/resources/application.yml
Labels: BE, 🚑 버그

#739 애플 로그인 시 이미 가입한 유저라면 회원가입 실패 기능 구현
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/implement/AppleUserInfoProvider.java
  backend/src/main/java/mouda/backend/member/implement/MemberFinder.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/mouda/backend/auth/business/AppleAuthServiceTest.java
Labels: BE, 🚑 버그

#743 회원 객체의 상태를 직접 변경하여 더티체킹 하도록 수정
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/implement/MemberWriter.java
  backend/src/test/java/mouda/backend/auth/business/KakaoAuthServiceTest.java
Labels: BE, 🚑 버그

#740 다락방 멤버 프로필 조회 기능 구현
  backend/src/main/java/mouda/backend/chat/domain/Participant.java
  backend/src/main/java/mouda/backend/chat/implement/BetAttributeManager.java
  backend/src/main/java/mouda/backend/chat/implement/BetChatPreviewManager.java
  backend/src/main/java/mouda/backend/chat/implement/BetParticipantResolver.java
  backend/src/main/java/mouda/backend/chat/implement/MoimChatPreviewManager.java
  backend/src/main/java/mouda/backend/chat/implement/MoimParticipantResolver.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ChatFindDetailResponse.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ChatPreviewResponse.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ChatRoomDetailsResponse.java
  backend/src/main/java/mouda/backend/chat/presentation/response/ParticipantResponse.java
  backend/src/main/java/mouda/backend/darakbangmember/business/DarakbangMemberService.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/DarakbangMemberFinder.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/controller/DarakbangMemberController.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/controller/swagger/DarakbangMemberSwagger.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/response/DarakbangMemberProfileResponse.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/response/DarakbangMemberResponse.java
  backend/src/main/java/mouda/backend/moim/presentation/response/chamyo/ChamyoFindAllResponse.java
  backend/src/test/java/mouda/backend/chat/implement/ChatRoomDetailsFinderTest.java
  backend/src/test/java/mouda/backend/darakbangmember/implement/DarakbangMemberFinderTest.java
Labels: BE, 🌱 기능추가

#733 사용자 전환 QA를 통한 사용자 전환 분기처리 버그 수정
  frontend/src/pages/Login/DataMigrationPage/OAuthMigrationResult/OAuthMigrationResultPage.tsx
  frontend/src/pages/Login/OAuthLoginPage/OAuthLoginPage.tsx
Labels: FE, 🚑 버그

#735 2차 QA 버그 수정
  frontend/src/layouts/ChattingPreviewLayout/ChattingPreviewContainer/ChattingPreviewContainer.style.ts
  frontend/src/pages/Bet/BetResultPage/BetResultPage.tsx
  frontend/src/pages/Bet/components/Roulette/DrawRoulette.ts
  frontend/src/pages/Bet/components/Roulette/Roulette.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChatFilterTagList/ChatFilterTagList.styles.ts
  frontend/src/pages/Chatting/ChatPage/components/ChattingPreview/ChattingPreview.style.ts
Labels: FE, 🚨 긴급

#745 HEIC 파일 포맷 지원을 위한 convert로직 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/assets/loading.gif
  frontend/src/components/Fallback/HappyFallback/HappyFallback.style.ts
  frontend/src/pages/Login/OAuthLoginPage/OAuthLoginPage.tsx
  frontend/src/pages/Moim/MainPage/MainPage.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Mypage/hook/useMyPage.ts
Labels: FE, 🌱 기능추가

#747 알림 작업 구조 개선 & 특정 알림 메시지 구체화
  backend/src/main/java/mouda/backend/chat/business/ChatService.java
  backend/src/main/java/mouda/backend/chat/domain/ChatNotificationEvent.java
  backend/src/main/java/mouda/backend/chat/implement/notification/ChatNotificationEventHandler.java
  backend/src/main/java/mouda/backend/chat/implement/notification/ChatNotificationSender.java
  backend/src/main/java/mouda/backend/chat/implement/notification/ChatRecipientFinder.java
  backend/src/main/java/mouda/backend/moim/business/ChamyoService.java
  backend/src/main/java/mouda/backend/moim/business/CommentService.java
  backend/src/main/java/mouda/backend/moim/business/MoimService.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/AbstractMoimRelatedNotificationEventHandler.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/ChamyoNotificationEventHandler.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/ChamyoRecipientFinder.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/CommentNotificationEventHandler.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/CommentRecipientFinder.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/CommentRecipients.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/MoimNotificationEventHandler.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/MoimRecipientFinder.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/MoimRelatedNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/event/ChamyoNotificationEvent.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/event/CommentNotificationEvent.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/event/MoimCreateNotificationEvent.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/event/MoimEditedNotificationEvent.java
  backend/src/main/java/mouda/backend/moim/implement/notificiation/event/MoimStatusChangeNotificationEvent.java
  backend/src/main/java/mouda/backend/moim/implement/sender/ChamyoNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/sender/CommentNotificationSender.java
  backend/src/main/java/mouda/backend/moim/implement/sender/MoimNotificationSender.java
  backend/src/main/java/mouda/backend/notification/business/NotificationService.java
  backend/src/main/java/mouda/backend/notification/domain/FcmFailedResponse.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationPayload.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationSendEvent.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationType.java
  backend/src/main/java/mouda/backend/notification/exception/NotificationErrorMessage.java
  backend/src/main/java/mouda/backend/notification/implement/NotificationProcessor.java
  backend/src/main/java/mouda/backend/notification/implement/NotificationSendEventHandler.java
  backend/src/main/java/mouda/backend/notification/implement/NotificationWriter.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/AsyncFcmNotificationSender.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/FcmNotificationSender.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/FcmResponseHandler.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/FcmRetryableChecker.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/token/FcmTokenFinder.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/token/FcmTokenScheduler.java
  backend/src/main/java/mouda/backend/notification/implement/filter/ChatRoomSubscriptionFilter.java
  backend/src/main/java/mouda/backend/notification/implement/filter/MoimCreatedSubscriptionFilter.java
  backend/src/main/java/mouda/backend/notification/implement/filter/NonSubscriptionFilter.java
  backend/src/main/java/mouda/backend/notification/implement/filter/SubscriptionFilter.java
  backend/src/main/java/mouda/backend/notification/implement/filter/SubscriptionFilterRegistry.java
  backend/src/test/java/mouda/backend/chat/ChatAsyncTest.java
  backend/src/test/java/mouda/backend/chat/implement/ChatRecipientFinderTest.java
  backend/src/test/java/mouda/backend/moim/business/ChamyoAsyncTest.java
  backend/src/test/java/mouda/backend/moim/business/CommentAsyncTest.java
  backend/src/test/java/mouda/backend/moim/business/MoimAsyncTest.java
  backend/src/test/java/mouda/backend/moim/implement/finder/ChamyoRecipientFinderTest.java
  backend/src/test/java/mouda/backend/moim/implement/finder/CommentRecipientsFinderTest.java
  backend/src/test/java/mouda/backend/moim/implement/finder/MoimRecipientFinderTest.java
  backend/src/test/java/mouda/backend/notification/domain/NotificationSendEventTest.java
  backend/src/test/java/mouda/backend/notification/implement/NotificationAsyncTest.java
  backend/src/test/java/mouda/backend/notification/implement/filter/ChatRoomSubscriptionFilterTest.java
Labels: BE, 🚑 버그

#759 중복 모임 채팅방 생성 버그 픽스
  backend/src/main/java/mouda/backend/chat/exception/ChatErrorMessage.java
  backend/src/main/java/mouda/backend/chat/implement/ChatRoomValidator.java
  backend/src/main/java/mouda/backend/chat/implement/ChatRoomWriter.java
  backend/src/main/java/mouda/backend/chat/infrastructure/ChatRoomRepository.java
  backend/src/test/java/mouda/backend/chat/implement/ChatRoomValidatorTest.java
  backend/src/test/java/mouda/backend/chat/implement/ChatRoomWriterTest.java
Labels: BE, 🚑 버그

#763 전송 실패한 알림에 대한 로깅 구체화
  backend/src/main/java/mouda/backend/notification/domain/FcmFailedResponse.java
  backend/src/main/java/mouda/backend/notification/implement/fcm/FcmRetryableChecker.java
Labels: BE, 🚑 버그

#756 프로필 바텀 시트 사용자 프로필 사진 안보이는 문제 해결
  frontend/src/apis/responseTypes.ts
  frontend/src/components/MemberCard/MemberCard.tsx
  frontend/src/hooks/useProfileBottomSheet.tsx
  frontend/src/pages/Bet/BetDetailPage/components/ProfileCard/ProfileCard.tsx
  frontend/src/pages/Chatting/ChattingRoomPage/components/ChatProfileImage/ChatProfileImage.tsx
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileCard/ProfileCard.tsx
Labels: FE, 🚑 버그

#757 z-index 문제로 프로필 이미지가 보이지 않는 문제 수정
  frontend/src/components/KebabMenu/KebabMenu.style.ts
  frontend/src/components/KebabMenu/KebabMenu.tsx
  frontend/src/components/ProfileFrame/ProfileFrame.style.ts
Labels: FE, 🚑 버그

#765 로그인 플로우 접근성 개선
  frontend/src/pages/Login/HomePage/HomePage.style.ts
  frontend/src/pages/Login/HomePage/HomePage.tsx
Labels: FE, 🌱 기능추가

#758 서버가 사용하는 스크립트 변경
  .github/workflows/be-rolling-deploy.yml
  .github/workflows/cd-prod.yml
Labels: BE, ⚙ 환경설정

#780 댓글에서 프로필 응답 누락 해결
  backend/src/main/java/mouda/backend/chat/implement/notification/ChatNotificationEvent.java
  backend/src/main/java/mouda/backend/chat/implement/notification/ChatNotificationEventHandler.java
  backend/src/main/java/mouda/backend/chat/implement/notification/ChatNotificationSender.java
  backend/src/main/java/mouda/backend/moim/domain/CommentRecipients.java
  backend/src/main/java/mouda/backend/moim/presentation/response/comment/CommentResponse.java
  backend/src/main/java/mouda/backend/notification/domain/NotificationEvent.java
  backend/src/test/java/mouda/backend/common/fixture/CommentFixture.java
  backend/src/test/java/mouda/backend/moim/business/CommentAsyncTest.java
  backend/src/test/java/mouda/backend/moim/comment/domain/CommentTest.java
  backend/src/test/java/mouda/backend/moim/implement/finder/CommentFinderTest.java
  backend/src/test/java/mouda/backend/moim/implement/writer/CommentWriterTest.java
  backend/src/test/java/mouda/backend/moim/moim/business/MoimServiceTest.java
Labels: BE, 🚑 버그

#776 모임 목록, 룰렛 목록 플러스 버튼에 의해 아이템 가려지는 문제 해결
  frontend/src/components/PlusButton/PlusButton.style.ts
  frontend/src/layouts/components/FixedCreationButtonWrapper/FixedCreationButtonWrapper.style.ts
Labels: FE, 🚑 버그

#782 프론트 따닥 문제 해결
  frontend/src/pages/Bet/BetCreationPage/BetCreationPage.tsx
  frontend/src/pages/Bet/BetDetailPage/BetDetailPage.tsx
  frontend/src/pages/Darakbang/DarakbangCreationPage/DarakbangCreationPage.tsx
  frontend/src/pages/Moim/MoimCreationPage/MoimCreationPage.tsx
  frontend/src/pages/Moim/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/Moim/MoimModifyPage/MoimModifyPage.tsx
Labels: FE, 🚑 버그

#774 모임 수정 페이지 Time validate가 현재 날짜에 종속되지 않는 문제 수정
  frontend/src/pages/Moim/MoimModifyPage/MoimModifyPage.hook.ts
Labels: FE, 🚑 버그

#785 다락방 초대 코드로 들어오는 분기처리 변경
  frontend/src/App.tsx
  frontend/src/pages/Darakbang/DarakbangSelectOptionPage/DarakbangSelectOptionPage.tsx
  frontend/src/pages/Navigator/DarakbangInvitationRoute.tsx
  frontend/src/routes/router.tsx
Labels: FE, 🚨 긴급

#792 cd-prod.yml 삭제 및 충돌 해결
  .github/workflows/cd-prod.yml
Labels: BE, ⚙ 환경설정
