Repository woowacourse-teams/2024-mouda, pull requests merged in 2024-09, with the labels that each got.

#519 불필요한 정보 로깅 제외 및 원활한 스웨거 테스트를 위한 설정
  backend/src/main/java/mouda/backend/aop/logging/RequestLoggingAspect.java
  backend/src/main/java/mouda/backend/auth/business/AuthService.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/swagger/AuthSwagger.java
  backend/src/main/java/mouda/backend/common/config/WebMvcConfig.java
  backend/src/main/java/mouda/backend/moim/presentation/controller/ChatController.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/logback-spring.xml
Labels: BE, ⚒️ 리팩터링

#524 테이블 unique 제약 조건을 활용해 참여 시 동시성 이슈 해결
  backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/main/java/mouda/backend/moim/business/ChamyoService.java
  backend/src/main/java/mouda/backend/moim/domain/Chamyo.java
  backend/src/main/java/mouda/backend/moim/infrastructure/MoimRepository.java
  backend/src/test/java/mouda/backend/darakbang/business/DarakbangServiceTest.java
  backend/src/test/java/mouda/backend/moim/chamyo/business/ChamyoServiceTest.java
Labels: BE, 🚑 버그

#515 아이폰 사용자를 위한 새로고침 버튼 추가
  frontend/src/common/assets/refresh.svg
  frontend/src/components/RefreshButton/RefreshButton.style.ts
  frontend/src/components/RefreshButton/RefreshButton.tsx
  frontend/src/layouts/PleaseLayout/PleaseLayout.tsx
  frontend/src/pages/ChatPage/ChatPage.stories.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.stories.tsx
  frontend/src/pages/MoimDetailPage/MoimDetailPage.tsx
  frontend/src/pages/NotificationPage/NotificationPage.stories.tsx
  frontend/src/pages/NotificationPage/NotificationPage.tsx
  frontend/src/pages/PleasePage/PleasePage.stories.tsx
  frontend/src/pages/PleasePage/PleasePage.tsx
Labels: FE, 🌱 기능추가

#529 input에 대한 유효성 검사에 대한 결과를 사용자가 즉각 파악할 수 있게 구현
  frontend/src/components/Input/MoimInpit.stories.tsx
  frontend/src/components/Input/MoimInput.style.ts
  frontend/src/components/Input/MoimInput.tsx
  frontend/src/components/TextArea/LabeledTextArea.style.ts
  frontend/src/components/TextArea/LabeledTextArea.tsx
  frontend/src/pages/MoimModifyPage/MoimModifyPage.constant.ts
  frontend/src/pages/MoimModifyPage/MoimModifyPage.hook.ts
  frontend/src/pages/MoimModifyPage/MoimModifyPage.stories.tsx
  frontend/src/pages/MoimModifyPage/MoimModifyPage.tsx
  frontend/src/pages/MoimModifyPage/MoimModifyPage.util.ts
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.constant.ts
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.stories.tsx
  frontend/src/pages/PleaseCreationPage/PleaseCreationPage.tsx
Labels: FE, 🌱 기능추가

#532 모임 생성 후 뒤로가기 시 만들기 페이지로 이동하는 문제 해결
  frontend/src/pages/MoimCreationPage/MoimCreationPage.hook.ts
Labels: FE, 🚑 버그

#536 파이어베이스 서비스워커가 동작이 안되는 곳에서도 동작 제한
  frontend/src/service/forgroundMessage.ts
  frontend/src/service/initFirebase.ts
  frontend/src/service/notification.ts
  frontend/src/utils/checkCanUseFirebase.ts
Labels: FE, 🚑 버그

#539 시간 validate가 내가 선택한 시간을 반영하지 않는 문제 수정
  frontend/src/pages/MoimModifyPage/MoimModifyPage.constant.ts
  frontend/src/pages/MoimModifyPage/MoimModifyPage.tsx
  frontend/src/pages/MoimModifyPage/MoimModifyPage.util.ts
Labels: FE, 🚑 버그

#549 대소문자 변경 파일이 중복되어 있어 캐시되어 있는 데이터 삭제
  frontend/src/pages/Chatting/ChatPage/Components/Chat/Chat.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/Chat/Chat.tsx
  frontend/src/pages/Chatting/ChatPage/Components/Chat/Chatstyle.ts
  frontend/src/pages/Chatting/ChatPage/Components/ChatBottomMenu/ChatBottomMenu.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatBottomMenu/ChatBottomMenu.style.ts
  frontend/src/pages/Chatting/ChatPage/Components/ChatBottomMenu/ChatBottomMenu.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatBubble/ChatBubble.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatBubble/ChatBubble.style.ts
  frontend/src/pages/Chatting/ChatPage/Components/ChatBubble/ChatBubble.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatBubble/ChatChildren/ChatChildren.style.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatBubble/ChatChildren/ChatChildren.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatList/ChatList.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatList/ChatList.style.ts
  frontend/src/pages/Chatting/ChatPage/Components/ChatList/ChatList.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatMenuItem/ChatMenuItem.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChatMenuItem/ChatMenuItem.style.ts
  frontend/src/pages/Chatting/ChatPage/Components/ChatMenuItem/ChatMenuItem.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChattingFooter/ChattingFooter.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/ChattingFooter/ChattingFooter.style.ts
  frontend/src/pages/Chatting/ChatPage/Components/ChattingFooter/ChattingFooter.tsx
  frontend/src/pages/Chatting/ChatPage/Components/DateTimeModalContent/DateTimeModalContent.stories.tsx
  frontend/src/pages/Chatting/ChatPage/Components/DateTimeModalContent/DateTimeModalContent.style.ts
  frontend/src/pages/Chatting/ChatPage/Components/DateTimeModalContent/DateTimeModalContent.tsx
Labels: FE, 🚑 버그

#540 다락방, 다락방 멤버 기능 리팩토링
  backend/src/main/java/mouda/backend/darakbang/business/DarakbangService.java
  backend/src/main/java/mouda/backend/darakbang/domain/Darakbang.java
  backend/src/main/java/mouda/backend/darakbang/domain/Darakbangs.java
  backend/src/main/java/mouda/backend/darakbang/implement/DarakbangFinder.java
  backend/src/main/java/mouda/backend/darakbang/implement/DarakbangValidator.java
  backend/src/main/java/mouda/backend/darakbang/implement/DarakbangWriter.java
  backend/src/main/java/mouda/backend/darakbang/implement/InvitationCodeGenerator.java
  backend/src/main/java/mouda/backend/darakbang/presentation/request/DarakbangCreateRequest.java
  backend/src/main/java/mouda/backend/darakbang/presentation/request/DarakbangEnterRequest.java
  backend/src/main/java/mouda/backend/darakbang/presentation/response/DarakbangResponse.java
  backend/src/main/java/mouda/backend/darakbang/presentation/response/DarakbangResponses.java
  backend/src/main/java/mouda/backend/darakbangmember/business/DarakbangMemberService.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakBangMemberRole.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMember.java
  backend/src/main/java/mouda/backend/darakbangmember/domain/DarakbangMembers.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/DarakbangMemberFinder.java
  backend/src/main/java/mouda/backend/darakbangmember/implement/DarakbangMemberWriter.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/response/DarakbangMemberResponses.java
  backend/src/main/java/mouda/backend/darakbangmember/presentation/response/DarakbangMemberRoleResponse.java
  backend/src/main/java/mouda/backend/member/implement/MemberValidator.java
  backend/src/test/java/mouda/backend/common/fixture/DarakbangFixture.java
  backend/src/test/java/mouda/backend/darakbang/business/DarakbangServiceTest.java
  backend/src/test/java/mouda/backend/darakbang/implement/DarakbangFinderTest.java
  backend/src/test/java/mouda/backend/darakbang/implement/DarakbangValidatorTest.java
  backend/src/test/java/mouda/backend/darakbang/implement/DarakbangWriterTest.java
  backend/src/test/java/mouda/backend/darakbang/implement/InvitationCodeGeneratorTest.java
  backend/src/test/java/mouda/backend/darakbangmember/implement/DarakbangMemberFinderTest.java
  backend/src/test/java/mouda/backend/darakbangmember/implement/DarakbangMemberWriterTest.java
  backend/src/test/java/mouda/backend/member/implement/MemberValidatorTest.java
Labels: BE, ⚒️ 리팩터링

#541 해주세요, 관심있어요 도메인 리팩토링
  backend/src/main/java/mouda/backend/please/business/InterestService.java
  backend/src/main/java/mouda/backend/please/business/PleaseService.java
  backend/src/main/java/mouda/backend/please/domain/PleaseWithInterest.java
  backend/src/main/java/mouda/backend/please/domain/PleaseWithInterests.java
  backend/src/main/java/mouda/backend/please/implement/InterestFinder.java
  backend/src/main/java/mouda/backend/please/implement/InterestValidator.java
  backend/src/main/java/mouda/backend/please/implement/InterestWriter.java
  backend/src/main/java/mouda/backend/please/implement/PleaseFinder.java
  backend/src/main/java/mouda/backend/please/implement/PleaseValidator.java
  backend/src/main/java/mouda/backend/please/implement/PleaseWriter.java
  backend/src/main/java/mouda/backend/please/presentation/request/PleaseCreateRequest.java
  backend/src/main/java/mouda/backend/please/presentation/response/PleaseFindAllResponse.java
  backend/src/main/java/mouda/backend/please/presentation/response/PleaseFindAllResponses.java
  backend/src/test/java/mouda/backend/common/fixture/PleaseFixture.java
  backend/src/test/java/mouda/backend/please/business/PleaseServiceTest.java
  backend/src/test/java/mouda/backend/please/implement/InterestFinderTest.java
  backend/src/test/java/mouda/backend/please/implement/InterestWriterTest.java
  backend/src/test/java/mouda/backend/please/implement/PleaseFinderTest.java
  backend/src/test/java/mouda/backend/please/implement/PleaseValidatorTest.java
Labels: BE, ⚒️ 리팩터링

#562 MASTER - SLAVE 적용을 위한 Springboot 설정 추가
  backend/src/main/java/mouda/backend/common/config/data/DataSourceConfiguration.java
  backend/src/main/java/mouda/backend/common/config/data/RoutingDataSource.java
  backend/src/main/resources/application.yml
  backend/src/test/java/mouda/backend/common/config/NoTransactionExtension.java
  backend/src/test/java/mouda/backend/common/config/WithTransactionalTest.java
  backend/src/test/java/mouda/backend/common/config/data/RoutingDataSourceTest.java
Labels: BE, 🌱 기능추가

#574 DB 환경설정 수정
  backend/src/main/resources/application-prod.yml
Labels: BE, ⚙ 환경설정

#550 프론트엔드 dev 배포 쉘 스크립트 대상 변경
  .github/workflows/cd-frontend.yml
Labels: FE, ⚙ 환경설정

#555 MSW환경에서 카카오톡 로그인이 필요한 문제 수정
  frontend/src/apis/endPoints.ts
  frontend/src/mocks/handler/moimHandler.ts
  frontend/src/service/forgroundMessage.ts
  frontend/src/utils/tokenManager.ts
Labels: FE, 🚑 버그

#557 프론트엔트 성능 개선을 위한 수정 사항 반영(에셋, 번들 크기)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/common/assets/default_profile.png
  frontend/src/common/assets/fonts/woff2/PretendardVariable.woff2
  frontend/src/common/assets/regret_cat.png
  frontend/src/common/assets/regret_cat.webp
  frontend/src/common/font.style.ts
  frontend/src/components/MissingFallback/MissingFallback.tsx
  frontend/src/components/UserPreview/UserPreview.style.ts
  frontend/src/custom.d.ts
  frontend/src/index.tsx
  frontend/webpack.common.js
  frontend/webpack.prod.js
Labels: FE, ⚒️ 리팩터링, ⚙ 환경설정

#567 코드 스플리팅 적용
  frontend/src/routes/router.tsx
  frontend/webpack.prod.js
Labels: FE, ⚒️ 리팩터링

#578 번들 분석기가 자동으로 페이지를 open 하는 것을 방지
  frontend/webpack.prod.js
Labels: FE, ⚙ 환경설정

#563 인증 관련 인터페이스 분리 및 애플 서버 연동
  .github/workflows/cd-frontend.yml
  .github/workflows/cicd-backend-dev.yml
  backend/src/main/java/mouda/backend/auth/Infrastructure/AppleOauthClient.java
  backend/src/main/java/mouda/backend/auth/Infrastructure/KakaoOauthClient.java
  backend/src/main/java/mouda/backend/auth/Infrastructure/OauthClient.java
  backend/src/main/java/mouda/backend/auth/Infrastructure/response/TokenResponse.java
  backend/src/main/java/mouda/backend/auth/business/AppleAuthService.java
  backend/src/main/java/mouda/backend/auth/business/AuthService.java
  backend/src/main/java/mouda/backend/auth/business/KakaoAuthService.java
  backend/src/main/java/mouda/backend/auth/exception/AuthErrorMessage.java
  backend/src/main/java/mouda/backend/auth/implement/JwtProvider.java
  backend/src/main/java/mouda/backend/auth/implement/LoginManager.java
  backend/src/main/java/mouda/backend/auth/presentation/controller/AuthController.java
  backend/src/main/java/mouda/backend/common/config/RestClientConfig.java
  backend/src/main/java/mouda/backend/common/config/argumentresolver/LoginDarakbangMemberArgumentResolver.java
  backend/src/main/java/mouda/backend/common/config/argumentresolver/LoginMemberArgumentResolver.java
  backend/src/main/java/mouda/backend/common/config/interceptor/AuthenticationCheckInterceptor.java
  backend/src/main/java/mouda/backend/darakbangmember/business/DarakbangMemberService.java
  backend/src/main/java/mouda/backend/member/domain/LoginDetail.java
  backend/src/main/java/mouda/backend/member/domain/Member.java
  backend/src/main/java/mouda/backend/member/domain/OauthType.java
  backend/src/main/java/mouda/backend/member/infrastructure/MemberRepository.java
  backend/src/main/java/mouda/backend/notification/presentation/controller/NotificationController.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/mouda/backend/auth/implement/LoginManagerTest.java
  backend/src/test/java/mouda/backend/auth/implement/MemberFinderTest.java
  backend/src/test/java/mouda/backend/common/fixture/MemberFixture.java
  backend/src/test/java/mouda/backend/moim/chat/business/ChatServiceTest.java
  backend/src/test/java/mouda/backend/notification/business/NotificationServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/test-data.sql
Labels: BE, 🌱 기능추가

#580 svg형식이 url일 때, svg파일을 불러오지 못하는 문제가 발생
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.style.ts
  frontend/src/components/Funnel/FunnelTextArea/FunnelTextArea.style.ts
  frontend/src/components/RefreshButton/RefreshButton.style.ts
  frontend/src/components/TextArea/LabeledTextArea.style.ts
  frontend/src/hooks/useStatePersist.ts
  frontend/src/layouts/HomeLayout.tsx/HomeHeader/HomeHeader.style.ts
  frontend/src/pages/Chatting/ChatPage/components/ChattingFooter/ChattingFooter.style.ts
  frontend/src/pages/Moim/MoimDetailPage/components/ProfileList/ProfileList.style.ts
  frontend/src/pages/Notification/components/NotificationList/NotificationCard/NotificationCard.style.ts
  frontend/src/service/notification.ts
  frontend/webpack.common.js
Labels: FE, 🚑 버그, ⚙ 환경설정

#592 데모데이 버그 수정
  frontend/src/apis/endPoints.ts
  frontend/src/common/common.style.ts
  frontend/src/components/DarakbangNameWrapper/DarakbangNameWrapper.tsx
  frontend/src/components/NavigationBar/NavigationBarItem/NavigationBarItem.tsx
  frontend/src/mocks/handler/chatHandler.ts
  frontend/src/pages/Chatting/ChatPage/ChatPage.tsx
  frontend/src/pages/Chatting/ChatPage/components/ChattingFooter/ChattingFooter.tsx
  frontend/src/pages/Darakbang/DarakbangInvitationPage/DarakbangInvitationPage.tsx
  frontend/src/pages/Darakbang/DarakbangLandingPage/DarakbangLandingPage.tsx
  frontend/src/pages/Moim/MainPage/MainPage.tsx
  frontend/src/pages/Moim/MainPage/components/HomeMainContent/MyMoim/MyMoimListFilters/MyMoimListFilterTag/MyMoimListFilterTag.tsx
  frontend/src/pages/Moim/MainPage/components/MoimTabBar/MoimTabBar.tsx
  frontend/src/pages/Mypage/MyPage.tsx
  frontend/src/pages/Mypage/components/MineInfoCard/MineInfoCard.tsx
  frontend/src/pages/Navigator/DarakbangInvitationRoute.tsx
  frontend/src/pages/Navigator/SlashRoute.tsx
  frontend/src/pages/Please/PleasePage/PleasePage.tsx
  frontend/src/pages/Please/PleasePage/components/PleaseList/PleaseCardList/PleaseCard/PleaseCard.tsx
  frontend/src/utils/formatters.ts
Labels: FE, 🚑 버그
